// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.llvm

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class LLVMLinkage(
    public val `value`: Int,
) {
    ExternalLinkage(0),

    /**
     * < Externally visible function
     */
    AvailableExternallyLinkage(1),
    LinkOnceAnyLinkage(2),

    /**
     * < Keep one copy of function when linking (inline)
     */
    LinkOnceODRLinkage(3),

    /**
     * < Same, but only replaced by something
     * equivalent.
     */
    LinkOnceODRAutoHideLinkage(4),

    /**
     * < Obsolete
     */
    WeakAnyLinkage(5),

    /**
     * < Keep one copy of function when linking (weak)
     */
    WeakODRLinkage(6),

    /**
     * < Same, but only replaced by something
     * equivalent.
     */
    AppendingLinkage(7),

    /**
     * < Special purpose, only applies to global arrays
     */
    InternalLinkage(8),

    /**
     * < Rename collisions when linking (static
     * functions)
     */
    PrivateLinkage(9),

    /**
     * < Like Internal, but omit from symbol table
     */
    DLLImportLinkage(10),

    /**
     * < Obsolete
     */
    DLLExportLinkage(11),

    /**
     * < Obsolete
     */
    ExternalWeakLinkage(12),

    /**
     * < ExternalWeak linkage description
     */
    GhostLinkage(13),

    /**
     * < Obsolete
     */
    CommonLinkage(14),

    /**
     * < Tentative definitions
     */
    LinkerPrivateLinkage(15),

    /**
     * < Like Private, but linker removes.
     */
    LinkerPrivateWeakLinkage(16),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            LLVMLinkage::class.java,
            "fromInt",
            MethodType.methodType(LLVMLinkage::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            LLVMLinkage::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): LLVMLinkage = when (value) {
            ExternalLinkage.value -> ExternalLinkage
            AvailableExternallyLinkage.value -> AvailableExternallyLinkage
            LinkOnceAnyLinkage.value -> LinkOnceAnyLinkage
            LinkOnceODRLinkage.value -> LinkOnceODRLinkage
            LinkOnceODRAutoHideLinkage.value -> LinkOnceODRAutoHideLinkage
            WeakAnyLinkage.value -> WeakAnyLinkage
            WeakODRLinkage.value -> WeakODRLinkage
            AppendingLinkage.value -> AppendingLinkage
            InternalLinkage.value -> InternalLinkage
            PrivateLinkage.value -> PrivateLinkage
            DLLImportLinkage.value -> DLLImportLinkage
            DLLExportLinkage.value -> DLLExportLinkage
            ExternalWeakLinkage.value -> ExternalWeakLinkage
            GhostLinkage.value -> GhostLinkage
            CommonLinkage.value -> CommonLinkage
            LinkerPrivateLinkage.value -> LinkerPrivateLinkage
            LinkerPrivateWeakLinkage.value -> LinkerPrivateWeakLinkage
            else -> error("enum not found")
        }
    }
}
