// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.llvm

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType

public enum class LLVMTypeKind(
    public val `value`: Int,
) {
    /**
     * < type with no size
     */
    VoidTypeKind(0),

    /**
     * < 16 bit floating point type
     */
    HalfTypeKind(1),

    /**
     * < 32 bit floating point type
     */
    FloatTypeKind(2),

    /**
     * < 64 bit floating point type
     */
    DoubleTypeKind(3),

    /**
     * < 80 bit floating point type (X87)
     */
    X86_FP80TypeKind(4),

    /**
     * < 128 bit floating point type (112-bit mantissa)
     */
    FP128TypeKind(5),

    /**
     * < 128 bit floating point type (two 64-bits)
     */
    PPC_FP128TypeKind(6),

    /**
     * < Labels
     */
    LabelTypeKind(7),

    /**
     * < Arbitrary bit width integers
     */
    IntegerTypeKind(8),

    /**
     * < Functions
     */
    FunctionTypeKind(9),

    /**
     * < Structures
     */
    StructTypeKind(10),

    /**
     * < Arrays
     */
    ArrayTypeKind(11),

    /**
     * < Pointers
     */
    PointerTypeKind(12),

    /**
     * < Fixed width SIMD vector type
     */
    VectorTypeKind(13),

    /**
     * < Metadata
     */
    MetadataTypeKind(14),

    /**
     * < Tokens
     */
    TokenTypeKind(16),

    /**
     * < Scalable SIMD vector type
     */
    ScalableVectorTypeKind(17),

    /**
     * < 16 bit brain floating point type
     */
    BFloatTypeKind(18),

    /**
     * < X86 AMX
     */
    X86_AMXTypeKind(19),

    /**
     * < Target extension type
     */
    TargetExtTypeKind(20),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            LLVMTypeKind::class.java,
            "fromInt",
            MethodType.methodType(LLVMTypeKind::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            LLVMTypeKind::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): LLVMTypeKind = when (value) {
            VoidTypeKind.value -> VoidTypeKind
            HalfTypeKind.value -> HalfTypeKind
            FloatTypeKind.value -> FloatTypeKind
            DoubleTypeKind.value -> DoubleTypeKind
            X86_FP80TypeKind.value -> X86_FP80TypeKind
            FP128TypeKind.value -> FP128TypeKind
            PPC_FP128TypeKind.value -> PPC_FP128TypeKind
            LabelTypeKind.value -> LabelTypeKind
            IntegerTypeKind.value -> IntegerTypeKind
            FunctionTypeKind.value -> FunctionTypeKind
            StructTypeKind.value -> StructTypeKind
            ArrayTypeKind.value -> ArrayTypeKind
            PointerTypeKind.value -> PointerTypeKind
            VectorTypeKind.value -> VectorTypeKind
            MetadataTypeKind.value -> MetadataTypeKind
            TokenTypeKind.value -> TokenTypeKind
            ScalableVectorTypeKind.value -> ScalableVectorTypeKind
            BFloatTypeKind.value -> BFloatTypeKind
            X86_AMXTypeKind.value -> X86_AMXTypeKind
            TargetExtTypeKind.value -> TargetExtTypeKind
            else -> error("enum not found")
        }
    }
}
