// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.llvm

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType

public enum class LLVMVisibility(
    public val `value`: Int,
) {
    DefaultVisibility(0),

    /**
     * < The GV is visible
     */
    HiddenVisibility(1),

    /**
     * < The GV is hidden
     */
    ProtectedVisibility(2),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            LLVMVisibility::class.java,
            "fromInt",
            MethodType.methodType(LLVMVisibility::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            LLVMVisibility::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): LLVMVisibility = when (value) {
            DefaultVisibility.value -> DefaultVisibility
            HiddenVisibility.value -> HiddenVisibility
            ProtectedVisibility.value -> ProtectedVisibility
            else -> error("enum not found")
        }
    }
}
