// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.llvm

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class LLVMInlineAsmDialect(
    public val `value`: Int,
) {
    ATT(0),
    Intel(1),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            LLVMInlineAsmDialect::class.java,
            "fromInt",
            MethodType.methodType(LLVMInlineAsmDialect::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            LLVMInlineAsmDialect::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): LLVMInlineAsmDialect = when (value) {
            ATT.value -> ATT
            Intel.value -> Intel
            else -> error("enum not found")
        }
    }
}
