// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.llvm

import java.lang.foreign.Arena
import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.SegmentAllocator
import java.lang.foreign.StructLayout
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle
import kotlin.Boolean
import kotlin.jvm.JvmField
import kotlin.jvm.JvmInline
import kotlin.jvm.JvmStatic

@JvmInline
public value class LLVMOrcCDependenceMapPair(
  public val `$mem`: MemorySegment,
) {
  public var JD: LLVMOrcJITDylibRef
    get() = LLVMOrcCDependenceMapPair.JDHandle.get(this.`$mem`, 0L) as MemorySegment
    set(`value`) {
      LLVMOrcCDependenceMapPair.JDHandle.set(this.`$mem`, 0L, value)
    }

  public var Names: LLVMOrcCSymbolsList
    get() = LLVMOrcCSymbolsList(LLVMOrcCDependenceMapPair.NamesHandle.invokeExact(this.`$mem`, 0L)
          as MemorySegment)
    set(`value`) {
      MemorySegment.copy(value.`$mem`, 0L, this.Names.`$mem`, 0L,
          LLVMOrcCSymbolsList.layout.byteSize())
    }

  public constructor(gc: Boolean) : this(kotlin.run {
      require(gc) { "Do not call this if gc is not want" }
      Arena.ofAuto().allocate(LLVMOrcCDependenceMapPair.layout)
  })

  public companion object {
    public val layout: StructLayout = MemoryLayout.structLayout(
      `$RuntimeHelper`.POINTER.withName("JD"),
      LLVMOrcCSymbolsList.layout.withName("Names"),
    ).withName("LLVMOrcCDependenceMapPair")

    @JvmField
    public val JDHandle: VarHandle = layout.varHandle(MemoryLayout.PathElement.groupElement("JD"))

    @JvmField
    public val NamesHandle: MethodHandle =
        layout.sliceHandle(MemoryLayout.PathElement.groupElement("Names"))

    @JvmStatic
    public fun allocate(alloc: SegmentAllocator): LLVMOrcCDependenceMapPair =
        LLVMOrcCDependenceMapPair(alloc.allocate(LLVMOrcCDependenceMapPair.layout))
  }
}
