// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.llvm

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType

public enum class LLVMCodeGenFileType(
    public val `value`: Int,
) {
    AssemblyFile(0),
    ObjectFile(1),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            LLVMCodeGenFileType::class.java,
            "fromInt",
            MethodType.methodType(LLVMCodeGenFileType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            LLVMCodeGenFileType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): LLVMCodeGenFileType = when (value) {
            AssemblyFile.value -> AssemblyFile
            ObjectFile.value -> ObjectFile
            else -> error("enum not found")
        }
    }
}
