// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.llvm

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType

public enum class LLVMCodeGenOptLevel(
    public val `value`: Int,
) {
    None(0),
    Less(1),
    Default(2),
    Aggressive(3),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            LLVMCodeGenOptLevel::class.java,
            "fromInt",
            MethodType.methodType(LLVMCodeGenOptLevel::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            LLVMCodeGenOptLevel::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): LLVMCodeGenOptLevel = when (value) {
            None.value -> None
            Less.value -> Less
            Default.value -> Default
            Aggressive.value -> Aggressive
            else -> error("enum not found")
        }
    }
}
