// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.llvm

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

/**
 *
 * \since prior to LTO_API_VERSION=3
 */
public enum class lto_codegen_model(
    public val `value`: Int,
) {
    CODEGENPICMODELSTATIC(0),
    CODEGENPICMODELDYNAMIC(1),
    CODEGENPICMODELDYNAMICNOPIC(2),
    CODEGENPICMODELDEFAULT(3),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            lto_codegen_model::class.java,
            "fromInt",
            MethodType.methodType(lto_codegen_model::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            lto_codegen_model::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): lto_codegen_model = when (value) {
            CODEGENPICMODELSTATIC.value -> CODEGENPICMODELSTATIC
            CODEGENPICMODELDYNAMIC.value -> CODEGENPICMODELDYNAMIC
            CODEGENPICMODELDYNAMICNOPIC.value -> CODEGENPICMODELDYNAMICNOPIC
            CODEGENPICMODELDEFAULT.value -> CODEGENPICMODELDEFAULT
            else -> error("enum not found")
        }
    }
}
