// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.llvm

import java.lang.foreign.*
import java.lang.invoke.VarHandle

/**
 *
 * Type to wrap a single object returned by ThinLTO.
 *
 * \since LTO_API_VERSION=18
 */
@JvmInline
public value class LTOObjectBuffer(
    public val `$mem`: MemorySegment,
) {
    public var Buffer: Pointer<Byte>
        get() = BufferHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            BufferHandle.set(this.`$mem`, 0L, value)
        }

    public var Size: ULong
        get() = (SizeHandle.get(this.`$mem`, 0L) as Long).toULong()
        set(`value`) {
            SizeHandle.set(this.`$mem`, 0L, value.toLong())
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("Buffer"),
            ValueLayout.JAVA_LONG.withName("Size"),
        ).withName("LTOObjectBuffer")

        @JvmField
        public val BufferHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("Buffer"))

        @JvmField
        public val SizeHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("Size"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): LTOObjectBuffer =
            LTOObjectBuffer(alloc.allocate(layout))
    }
}
