// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class CXChoice(
    public val `value`: Int,
) {
    /**
     *
     * Use the default value of an option that may depend on the process
     * environment.
     */
    Default(0),

    /**
     *
     * Enable the option.
     */
    Enabled(1),

    /**
     *
     * Disable the option.
     */
    Disabled(2),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXChoice::class.java,
            "fromInt",
            MethodType.methodType(CXChoice::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXChoice::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): CXChoice = when (value) {
            Default.value -> Default
            Enabled.value -> Enabled
            Disabled.value -> Disabled
            else -> error("enum not found")
        }
    }
}
