// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.foreign.*
import java.lang.invoke.VarHandle

/**
 *
 * A single result of code completion.
 */
@JvmInline
public value class CXCompletionResult(
    public val `$mem`: MemorySegment,
) {
    public var CursorKind: CXCursorKind
        get() = CXCursorKind.fromInt(CursorKindHandle.get(this.`$mem`, 0L) as Int)
        set(`value`) {
            CursorKindHandle.set(this.`$mem`, 0L, value.value)
        }

    public var CompletionString: CXCompletionString
        get() = CompletionStringHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            CompletionStringHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("CursorKind"),
            MemoryLayout.paddingLayout(4),
            `$RuntimeHelper`.POINTER.withName("CompletionString"),
        ).withName("CXCompletionResult")

        @JvmField
        public val CursorKindHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("CursorKind"))

        @JvmField
        public val CompletionStringHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("CompletionString"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): CXCompletionResult =
            CXCompletionResult(alloc.allocate(layout))
    }
}
