// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

/**
 *
 * Describes parameter passing direction for \\param or \\arg command.
 */
public enum class CXCommentParamPassDirection(
    public val `value`: Int,
) {
    /**
     *
     * The parameter is an input parameter.
     */
    In(0),

    /**
     *
     * The parameter is an output parameter.
     */
    Out(1),

    /**
     *
     * The parameter is an input and output parameter.
     */
    InOut(2),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXCommentParamPassDirection::class.java,
            "fromInt",
            MethodType.methodType(CXCommentParamPassDirection::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXCommentParamPassDirection::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): CXCommentParamPassDirection = when (value) {
            In.value -> In
            Out.value -> Out
            InOut.value -> InOut
            else -> error("enum not found")
        }
    }
}
