// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
public value class CXIdxCXXClassDeclInfo(
    public val `$mem`: MemorySegment,
) {
    public var declInfo: Pointer<CXIdxDeclInfo>
        get() = declInfoHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            declInfoHandle.set(this.`$mem`, 0L, value)
        }

    public var bases: Pointer<Pointer<CXIdxBaseClassInfo>>
        get() = basesHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            basesHandle.set(this.`$mem`, 0L, value)
        }

    public var numBases: UInt
        get() = (numBasesHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            numBasesHandle.set(this.`$mem`, 0L, value.toInt())
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("declInfo"),
            `$RuntimeHelper`.POINTER.withName("bases"),
            ValueLayout.JAVA_INT.withName("numBases"),
            MemoryLayout.paddingLayout(4),
        ).withName("CXIdxCXXClassDeclInfo")

        @JvmField
        public val declInfoHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("declInfo"))

        @JvmField
        public val basesHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("bases"))

        @JvmField
        public val numBasesHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("numBases"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): CXIdxCXXClassDeclInfo =
            CXIdxCXXClassDeclInfo(alloc.allocate(layout))
    }
}
