// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

/**
 *
 * Data for IndexerCallbacks#indexEntityReference.
 */
@JvmInline
public value class CXIdxEntityRefInfo(
    public val `$mem`: MemorySegment,
) {
    public var kind: CXIdxEntityRefKind
        get() = CXIdxEntityRefKind.fromInt(kindHandle.get(this.`$mem`, 0L) as Int)
        set(`value`) {
            kindHandle.set(this.`$mem`, 0L, value.value)
        }

    public var cursor: CXCursor
        get() = CXCursor(cursorHandle.invokeExact(this.`$mem`, 0L) as MemorySegment)
        set(`value`) {
            MemorySegment.copy(value.`$mem`, 0L, this.cursor.`$mem`, 0L, CXCursor.layout.byteSize())
        }

    public var loc: CXIdxLoc
        get() = CXIdxLoc(locHandle.invokeExact(this.`$mem`, 0L) as MemorySegment)
        set(`value`) {
            MemorySegment.copy(value.`$mem`, 0L, this.loc.`$mem`, 0L, CXIdxLoc.layout.byteSize())
        }

    public var referencedEntity: Pointer<CXIdxEntityInfo>
        get() = referencedEntityHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            referencedEntityHandle.set(this.`$mem`, 0L, value)
        }

    public var parentEntity: Pointer<CXIdxEntityInfo>
        get() = parentEntityHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            parentEntityHandle.set(this.`$mem`, 0L, value)
        }

    public var container: Pointer<CXIdxContainerInfo>
        get() = containerHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            containerHandle.set(this.`$mem`, 0L, value)
        }

    public var role: CXSymbolRole
        get() = CXSymbolRole.fromInt(roleHandle.get(this.`$mem`, 0L) as Int)
        set(`value`) {
            roleHandle.set(this.`$mem`, 0L, value.value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("kind"),
            MemoryLayout.paddingLayout(4),
            CXCursor.layout.withName("cursor"),
            CXIdxLoc.layout.withName("loc"),
            `$RuntimeHelper`.POINTER.withName("referencedEntity"),
            `$RuntimeHelper`.POINTER.withName("parentEntity"),
            `$RuntimeHelper`.POINTER.withName("container"),
            ValueLayout.JAVA_INT.withName("role"),
            MemoryLayout.paddingLayout(4),
        ).withName("CXIdxEntityRefInfo")

        @JvmField
        public val kindHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("kind"))

        @JvmField
        public val cursorHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("cursor"))

        @JvmField
        public val locHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("loc"))

        @JvmField
        public val referencedEntityHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("referencedEntity"))

        @JvmField
        public val parentEntityHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("parentEntity"))

        @JvmField
        public val containerHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("container"))

        @JvmField
        public val roleHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("role"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): CXIdxEntityRefInfo =
            CXIdxEntityRefInfo(alloc.allocate(layout))
    }
}
