// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

@JvmInline
public value class CXIdxBaseClassInfo(
    public val `$mem`: MemorySegment,
) {
    public var base: Pointer<CXIdxEntityInfo>
        get() = baseHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            baseHandle.set(this.`$mem`, 0L, value)
        }

    public var cursor: CXCursor
        get() = CXCursor(cursorHandle.invokeExact(this.`$mem`, 0L) as MemorySegment)
        set(`value`) {
            MemorySegment.copy(value.`$mem`, 0L, this.cursor.`$mem`, 0L, CXCursor.layout.byteSize())
        }

    public var loc: CXIdxLoc
        get() = CXIdxLoc(locHandle.invokeExact(this.`$mem`, 0L) as MemorySegment)
        set(`value`) {
            MemorySegment.copy(value.`$mem`, 0L, this.loc.`$mem`, 0L, CXIdxLoc.layout.byteSize())
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("base"),
            CXCursor.layout.withName("cursor"),
            CXIdxLoc.layout.withName("loc"),
        ).withName("CXIdxBaseClassInfo")

        @JvmField
        public val baseHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("base"))

        @JvmField
        public val cursorHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("cursor"))

        @JvmField
        public val locHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("loc"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): CXIdxBaseClassInfo =
            CXIdxBaseClassInfo(alloc.allocate(layout))
    }
}
