// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.foreign.*
import java.lang.invoke.MethodHandle

@JvmInline
public value class CXIdxContainerInfo(
    public val `$mem`: MemorySegment,
) {
    public var cursor: CXCursor
        get() = CXCursor(cursorHandle.invokeExact(this.`$mem`, 0L) as MemorySegment)
        set(`value`) {
            MemorySegment.copy(value.`$mem`, 0L, this.cursor.`$mem`, 0L, CXCursor.layout.byteSize())
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            CXCursor.layout.withName("cursor"),
        ).withName("CXIdxContainerInfo")

        @JvmField
        public val cursorHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("cursor"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): CXIdxContainerInfo =
            CXIdxContainerInfo(alloc.allocate(layout))
    }
}
