// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
public value class CXIdxObjCProtocolRefListInfo(
    public val `$mem`: MemorySegment,
) {
    public var protocols: Pointer<Pointer<CXIdxObjCProtocolRefInfo>>
        get() = protocolsHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            protocolsHandle.set(this.`$mem`, 0L, value)
        }

    public var numProtocols: UInt
        get() = (numProtocolsHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            numProtocolsHandle.set(this.`$mem`, 0L, value.toInt())
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("protocols"),
            ValueLayout.JAVA_INT.withName("numProtocols"),
            MemoryLayout.paddingLayout(4),
        ).withName("CXIdxObjCProtocolRefListInfo")

        @JvmField
        public val protocolsHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("protocols"))

        @JvmField
        public val numProtocolsHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("numProtocols"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): CXIdxObjCProtocolRefListInfo =
            CXIdxObjCProtocolRefListInfo(alloc.allocate(layout))
    }
}
