// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class CXIdxObjCContainerKind(
    public val `value`: Int,
) {
    ForwardRef(0),
    Interface(1),
    Implementation(2),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXIdxObjCContainerKind::class.java,
            "fromInt",
            MethodType.methodType(CXIdxObjCContainerKind::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXIdxObjCContainerKind::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): CXIdxObjCContainerKind = when (value) {
            ForwardRef.value -> ForwardRef
            Interface.value -> Interface
            Implementation.value -> Implementation
            else -> error("enum not found")
        }
    }
}
