// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.foreign.*

@JvmInline
public value class CXModuleMapDescriptorImpl(
    public val `$mem`: MemorySegment,
) {
    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
        ).withName("CXModuleMapDescriptorImpl")

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): CXModuleMapDescriptorImpl =
            CXModuleMapDescriptorImpl(alloc.allocate(layout))
    }
}
