// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

/**
 *
 * 'Qualifiers' written next to the return and parameter types in
 * Objective-C method declarations.
 */
public enum class CXObjCDeclQualifierKind(
    public val `value`: Int,
) {
    None(0x0),
    In(0x1),
    Inout(0x2),
    Out(0x4),
    Bycopy(0x8),
    Byref(0x10),
    Oneway(0x20),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXObjCDeclQualifierKind::class.java,
            "fromInt",
            MethodType.methodType(CXObjCDeclQualifierKind::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXObjCDeclQualifierKind::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): CXObjCDeclQualifierKind = when (value) {
            None.value -> None
            In.value -> In
            Inout.value -> Inout
            Out.value -> Out
            Bycopy.value -> Bycopy
            Byref.value -> Byref
            Oneway.value -> Oneway
            else -> error("enum not found")
        }
    }
}
