// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class CXRefQualifierKind(
    public val `value`: Int,
) {
    /**
     * No ref-qualifier was provided.
     */
    None(0),

    /**
     * An lvalue ref-qualifier was provided (\c &).
     */
    LValue(1),

    /**
     * An rvalue ref-qualifier was provided (\c &&).
     */
    RValue(2),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXRefQualifierKind::class.java,
            "fromInt",
            MethodType.methodType(CXRefQualifierKind::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXRefQualifierKind::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): CXRefQualifierKind = when (value) {
            None.value -> None
            LValue.value -> LValue
            RValue.value -> RValue
            else -> error("enum not found")
        }
    }
}
