// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.foreign.*
import java.lang.invoke.VarHandle

/**
 *
 * A character string.
 *
 * The \c CXString type is used to return strings from the interface when
 * the ownership of that string might differ from one call to the next.
 * Use \c clang_getCString() to retrieve the string data and, once finished
 * with the string data, call \c clang_disposeString() to free the string.
 */
@JvmInline
public value class CXString(
    public val `$mem`: MemorySegment,
) {
    public var `data`: Pointer<Unit>
        get() = dataHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            dataHandle.set(this.`$mem`, 0L, value)
        }

    public var private_flags: UInt
        get() = (private_flagsHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            private_flagsHandle.set(this.`$mem`, 0L, value.toInt())
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("data"),
            ValueLayout.JAVA_INT.withName("private_flags"),
            MemoryLayout.paddingLayout(4),
        ).withName("CXString")

        @JvmField
        public val dataHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("data"))

        @JvmField
        public val private_flagsHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("private_flags"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): CXString = CXString(alloc.allocate(layout))
    }
}
