// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
public value class CXStringSet(
    public val `$mem`: MemorySegment,
) {
    public var Strings: Pointer<CXString>
        get() = StringsHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            StringsHandle.set(this.`$mem`, 0L, value)
        }

    public var Count: UInt
        get() = (CountHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            CountHandle.set(this.`$mem`, 0L, value.toInt())
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("Strings"),
            ValueLayout.JAVA_INT.withName("Count"),
            MemoryLayout.paddingLayout(4),
        ).withName("CXStringSet")

        @JvmField
        public val StringsHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("Strings"))

        @JvmField
        public val CountHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("Count"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): CXStringSet = CXStringSet(alloc.allocate(layout))
    }
}
