// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.error

/**
 *
 * Describes the kind of type
 */
public enum class CXTypeKind(
    public val `value`: kotlin.Int,
) {
    /**
     *
     * Represents an invalid type (e.g., where no type is available).
     */
    Invalid(0),

    /**
     *
     * A type whose specific kind is not exposed via this
     * interface.
     */
    Unexposed(1),

    /**
     * Builtin types
     */
    Void(2),
    Bool(3),
    CharU(4),
    UChar(5),
    Char16(6),
    Char32(7),
    UShort(8),
    UInt(9),
    ULong(10),
    ULongLong(11),
    UInt128(12),
    CharS(13),
    SChar(14),
    WChar(15),
    Short(16),
    Int(17),
    Long(18),
    LongLong(19),
    Int128(20),
    Float(21),
    Double(22),
    LongDouble(23),
    NullPtr(24),
    Overload(25),
    Dependent(26),
    ObjCId(27),
    ObjCClass(28),
    ObjCSel(29),
    Float128(30),
    Half(31),
    Float16(32),
    ShortAccum(33),
    Accum(34),
    LongAccum(35),
    UShortAccum(36),
    UAccum(37),
    ULongAccum(38),
    BFloat16(39),
    Ibm128(40),
    FirstBuiltin(Void.value),
    LastBuiltin(Ibm128.value),
    Complex(100),
    Pointer(101),
    BlockPointer(102),
    LValueReference(103),
    RValueReference(104),
    Record(105),
    Enum(106),
    Typedef(107),
    ObjCInterface(108),
    ObjCObjectPointer(109),
    FunctionNoProto(110),
    FunctionProto(111),
    ConstantArray(112),
    Vector(113),
    IncompleteArray(114),
    VariableArray(115),
    DependentSizedArray(116),
    MemberPointer(117),
    Auto(118),

    /**
     *
     * Represents a type that was referred to using an elaborated type keyword.
     *
     * E.g., struct S, or via a qualified name, e.g., N::M::type, or both.
     */
    Elaborated(119),

    /**
     * OpenCL PipeType.
     */
    Pipe(120),

    /**
     * OpenCL builtin types.
     */
    OCLImage1dRO(121),
    OCLImage1dArrayRO(122),
    OCLImage1dBufferRO(123),
    OCLImage2dRO(124),
    OCLImage2dArrayRO(125),
    OCLImage2dDepthRO(126),
    OCLImage2dArrayDepthRO(127),
    OCLImage2dMSAARO(128),
    OCLImage2dArrayMSAARO(129),
    OCLImage2dMSAADepthRO(130),
    OCLImage2dArrayMSAADepthRO(131),
    OCLImage3dRO(132),
    OCLImage1dWO(133),
    OCLImage1dArrayWO(134),
    OCLImage1dBufferWO(135),
    OCLImage2dWO(136),
    OCLImage2dArrayWO(137),
    OCLImage2dDepthWO(138),
    OCLImage2dArrayDepthWO(139),
    OCLImage2dMSAAWO(140),
    OCLImage2dArrayMSAAWO(141),
    OCLImage2dMSAADepthWO(142),
    OCLImage2dArrayMSAADepthWO(143),
    OCLImage3dWO(144),
    OCLImage1dRW(145),
    OCLImage1dArrayRW(146),
    OCLImage1dBufferRW(147),
    OCLImage2dRW(148),
    OCLImage2dArrayRW(149),
    OCLImage2dDepthRW(150),
    OCLImage2dArrayDepthRW(151),
    OCLImage2dMSAARW(152),
    OCLImage2dArrayMSAARW(153),
    OCLImage2dMSAADepthRW(154),
    OCLImage2dArrayMSAADepthRW(155),
    OCLImage3dRW(156),
    OCLSampler(157),
    OCLEvent(158),
    OCLQueue(159),
    OCLReserveID(160),
    ObjCObject(161),
    ObjCTypeParam(162),
    Attributed(163),
    OCLIntelSubgroupAVCMcePayload(164),
    OCLIntelSubgroupAVCImePayload(165),
    OCLIntelSubgroupAVCRefPayload(166),
    OCLIntelSubgroupAVCSicPayload(167),
    OCLIntelSubgroupAVCMceResult(168),
    OCLIntelSubgroupAVCImeResult(169),
    OCLIntelSubgroupAVCRefResult(170),
    OCLIntelSubgroupAVCSicResult(171),
    OCLIntelSubgroupAVCImeResultSingleReferenceStreamout(172),
    OCLIntelSubgroupAVCImeResultDualReferenceStreamout(173),
    OCLIntelSubgroupAVCImeSingleReferenceStreamin(174),
    OCLIntelSubgroupAVCImeDualReferenceStreamin(175),

    /**
     * Old aliases for AVC OpenCL extension types.
     */
    OCLIntelSubgroupAVCImeResultSingleRefStreamout(172),
    OCLIntelSubgroupAVCImeResultDualRefStreamout(173),
    OCLIntelSubgroupAVCImeSingleRefStreamin(174),
    OCLIntelSubgroupAVCImeDualRefStreamin(175),
    ExtVector(176),
    Atomic(177),
    BTFTagAttributed(178),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXTypeKind::class.java,
            "fromInt",
            MethodType.methodType(CXTypeKind::class.java, kotlin.Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXTypeKind::class.java,
            "value",
            kotlin.Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: kotlin.Int): CXTypeKind = when (value) {
            Invalid.value -> Invalid
            Unexposed.value -> Unexposed
            Void.value -> Void
            Bool.value -> Bool
            CharU.value -> CharU
            UChar.value -> UChar
            Char16.value -> Char16
            Char32.value -> Char32
            UShort.value -> UShort
            UInt.value -> UInt
            ULong.value -> ULong
            ULongLong.value -> ULongLong
            UInt128.value -> UInt128
            CharS.value -> CharS
            SChar.value -> SChar
            WChar.value -> WChar
            Short.value -> Short
            Int.value -> Int
            Long.value -> Long
            LongLong.value -> LongLong
            Int128.value -> Int128
            Float.value -> Float
            Double.value -> Double
            LongDouble.value -> LongDouble
            NullPtr.value -> NullPtr
            Overload.value -> Overload
            Dependent.value -> Dependent
            ObjCId.value -> ObjCId
            ObjCClass.value -> ObjCClass
            ObjCSel.value -> ObjCSel
            Float128.value -> Float128
            Half.value -> Half
            Float16.value -> Float16
            ShortAccum.value -> ShortAccum
            Accum.value -> Accum
            LongAccum.value -> LongAccum
            UShortAccum.value -> UShortAccum
            UAccum.value -> UAccum
            ULongAccum.value -> ULongAccum
            BFloat16.value -> BFloat16
            Ibm128.value -> Ibm128
            FirstBuiltin.value -> FirstBuiltin
            LastBuiltin.value -> LastBuiltin
            Complex.value -> Complex
            Pointer.value -> Pointer
            BlockPointer.value -> BlockPointer
            LValueReference.value -> LValueReference
            RValueReference.value -> RValueReference
            Record.value -> Record
            Enum.value -> Enum
            Typedef.value -> Typedef
            ObjCInterface.value -> ObjCInterface
            ObjCObjectPointer.value -> ObjCObjectPointer
            FunctionNoProto.value -> FunctionNoProto
            FunctionProto.value -> FunctionProto
            ConstantArray.value -> ConstantArray
            Vector.value -> Vector
            IncompleteArray.value -> IncompleteArray
            VariableArray.value -> VariableArray
            DependentSizedArray.value -> DependentSizedArray
            MemberPointer.value -> MemberPointer
            Auto.value -> Auto
            Elaborated.value -> Elaborated
            Pipe.value -> Pipe
            OCLImage1dRO.value -> OCLImage1dRO
            OCLImage1dArrayRO.value -> OCLImage1dArrayRO
            OCLImage1dBufferRO.value -> OCLImage1dBufferRO
            OCLImage2dRO.value -> OCLImage2dRO
            OCLImage2dArrayRO.value -> OCLImage2dArrayRO
            OCLImage2dDepthRO.value -> OCLImage2dDepthRO
            OCLImage2dArrayDepthRO.value -> OCLImage2dArrayDepthRO
            OCLImage2dMSAARO.value -> OCLImage2dMSAARO
            OCLImage2dArrayMSAARO.value -> OCLImage2dArrayMSAARO
            OCLImage2dMSAADepthRO.value -> OCLImage2dMSAADepthRO
            OCLImage2dArrayMSAADepthRO.value -> OCLImage2dArrayMSAADepthRO
            OCLImage3dRO.value -> OCLImage3dRO
            OCLImage1dWO.value -> OCLImage1dWO
            OCLImage1dArrayWO.value -> OCLImage1dArrayWO
            OCLImage1dBufferWO.value -> OCLImage1dBufferWO
            OCLImage2dWO.value -> OCLImage2dWO
            OCLImage2dArrayWO.value -> OCLImage2dArrayWO
            OCLImage2dDepthWO.value -> OCLImage2dDepthWO
            OCLImage2dArrayDepthWO.value -> OCLImage2dArrayDepthWO
            OCLImage2dMSAAWO.value -> OCLImage2dMSAAWO
            OCLImage2dArrayMSAAWO.value -> OCLImage2dArrayMSAAWO
            OCLImage2dMSAADepthWO.value -> OCLImage2dMSAADepthWO
            OCLImage2dArrayMSAADepthWO.value -> OCLImage2dArrayMSAADepthWO
            OCLImage3dWO.value -> OCLImage3dWO
            OCLImage1dRW.value -> OCLImage1dRW
            OCLImage1dArrayRW.value -> OCLImage1dArrayRW
            OCLImage1dBufferRW.value -> OCLImage1dBufferRW
            OCLImage2dRW.value -> OCLImage2dRW
            OCLImage2dArrayRW.value -> OCLImage2dArrayRW
            OCLImage2dDepthRW.value -> OCLImage2dDepthRW
            OCLImage2dArrayDepthRW.value -> OCLImage2dArrayDepthRW
            OCLImage2dMSAARW.value -> OCLImage2dMSAARW
            OCLImage2dArrayMSAARW.value -> OCLImage2dArrayMSAARW
            OCLImage2dMSAADepthRW.value -> OCLImage2dMSAADepthRW
            OCLImage2dArrayMSAADepthRW.value -> OCLImage2dArrayMSAADepthRW
            OCLImage3dRW.value -> OCLImage3dRW
            OCLSampler.value -> OCLSampler
            OCLEvent.value -> OCLEvent
            OCLQueue.value -> OCLQueue
            OCLReserveID.value -> OCLReserveID
            ObjCObject.value -> ObjCObject
            ObjCTypeParam.value -> ObjCTypeParam
            Attributed.value -> Attributed
            OCLIntelSubgroupAVCMcePayload.value -> OCLIntelSubgroupAVCMcePayload
            OCLIntelSubgroupAVCImePayload.value -> OCLIntelSubgroupAVCImePayload
            OCLIntelSubgroupAVCRefPayload.value -> OCLIntelSubgroupAVCRefPayload
            OCLIntelSubgroupAVCSicPayload.value -> OCLIntelSubgroupAVCSicPayload
            OCLIntelSubgroupAVCMceResult.value -> OCLIntelSubgroupAVCMceResult
            OCLIntelSubgroupAVCImeResult.value -> OCLIntelSubgroupAVCImeResult
            OCLIntelSubgroupAVCRefResult.value -> OCLIntelSubgroupAVCRefResult
            OCLIntelSubgroupAVCSicResult.value -> OCLIntelSubgroupAVCSicResult
            OCLIntelSubgroupAVCImeResultSingleReferenceStreamout.value -> OCLIntelSubgroupAVCImeResultSingleReferenceStreamout
            OCLIntelSubgroupAVCImeResultDualReferenceStreamout.value -> OCLIntelSubgroupAVCImeResultDualReferenceStreamout
            OCLIntelSubgroupAVCImeSingleReferenceStreamin.value -> OCLIntelSubgroupAVCImeSingleReferenceStreamin
            OCLIntelSubgroupAVCImeDualReferenceStreamin.value -> OCLIntelSubgroupAVCImeDualReferenceStreamin
            OCLIntelSubgroupAVCImeResultSingleRefStreamout.value -> OCLIntelSubgroupAVCImeResultSingleRefStreamout
            OCLIntelSubgroupAVCImeResultDualRefStreamout.value -> OCLIntelSubgroupAVCImeResultDualRefStreamout
            OCLIntelSubgroupAVCImeSingleRefStreamin.value -> OCLIntelSubgroupAVCImeSingleRefStreamin
            OCLIntelSubgroupAVCImeDualRefStreamin.value -> OCLIntelSubgroupAVCImeDualRefStreamin
            ExtVector.value -> ExtVector
            Atomic.value -> Atomic
            BTFTagAttributed.value -> BTFTagAttributed
            else -> error("enum not found")
        }
    }
}
