// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

/**
 *
 * The type of an element in the abstract syntax tree.
 */
@JvmInline
public value class CXType(
    public val `$mem`: MemorySegment,
) {
    public var kind: CXTypeKind
        get() = CXTypeKind.fromInt(kindHandle.get(this.`$mem`, 0L) as Int)
        set(`value`) {
            kindHandle.set(this.`$mem`, 0L, value.value)
        }

    public val `data`: NativeArray<Pointer<Unit>>
        get() = dataHandle.invokeExact(this.`$mem`, 0L) as MemorySegment

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("kind"),
            MemoryLayout.paddingLayout(4),
            MemoryLayout.sequenceLayout(2L, `$RuntimeHelper`.POINTER).withName("data"),
        ).withName("CXType")

        @JvmField
        public val kindHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("kind"))

        @JvmField
        public val dataHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("data"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): CXType = CXType(alloc.allocate(layout))
    }
}
