// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.clang

import java.lang.foreign.*
import java.lang.invoke.VarHandle

/**
 *
 * Provides the contents of a file that has not yet been saved to disk.
 *
 * Each CXUnsavedFile instance provides the name of a file on the
 * system along with the current contents of that file that have not
 * yet been saved to disk.
 */
@JvmInline
public value class CXUnsavedFile(
    public val `$mem`: MemorySegment,
) {
    public var Filename: Pointer<Byte>
        get() = FilenameHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            FilenameHandle.set(this.`$mem`, 0L, value)
        }

    public var Contents: Pointer<Byte>
        get() = ContentsHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            ContentsHandle.set(this.`$mem`, 0L, value)
        }

    public var Length: ULong
        get() = (LengthHandle.get(this.`$mem`, 0L) as Long).toULong()
        set(`value`) {
            LengthHandle.set(this.`$mem`, 0L, value.toLong())
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("Filename"),
            `$RuntimeHelper`.POINTER.withName("Contents"),
            ValueLayout.JAVA_LONG.withName("Length"),
        ).withName("CXUnsavedFile")

        @JvmField
        public val FilenameHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("Filename"))

        @JvmField
        public val ContentsHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("Contents"))

        @JvmField
        public val LengthHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("Length"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): CXUnsavedFile =
            CXUnsavedFile(alloc.allocate(layout))
    }
}
