// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c.callback

import clang.c.`$RuntimeHelper`
import clang.c.CXChildVisitResult
import clang.c.CXClientData
import clang.c.CXCursor
import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles

fun interface CXCursorVisitor {
    fun invoke(
        cursor: CXCursor,
        parent: CXCursor,
        client_data: CXClientData,
    ): CXChildVisitResult

    fun allocate(arena: Arena): MemorySegment =
        Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

    companion object {
        @JvmStatic
        val invokeHandle: MethodHandle =
            MethodHandles.filterReturnValue(MethodHandles.lookup().unreflect(CXCursorVisitor::class.java.methods.find {
                it.name == "invoke"
            }
            ), CXChildVisitResult.toInt)

        @JvmStatic
        val fd: FunctionDescriptor = FunctionDescriptor.of(
            ValueLayout.JAVA_INT,
            CXCursor.layout,
            CXCursor.layout,
            `$RuntimeHelper`.POINTER,
        )
    }
}
