// this file is auto generated by endoqa kotlin ffi, modify it with caution
package llvm.c.callback

import llvm.c.`$RuntimeHelper`
import llvm.c.LLVMOrcExecutionSessionRef
import llvm.c.LLVMOrcObjectLayerRef
import llvm.c.Pointer
import java.lang.foreign.Arena
import java.lang.foreign.FunctionDescriptor
import java.lang.foreign.Linker
import java.lang.foreign.MemorySegment
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles

public fun interface LLVMOrcLLJITBuilderObjectLinkingLayerCreatorFunction {
    public fun invoke(
        Ctx: Pointer<Unit>,
        ES: LLVMOrcExecutionSessionRef,
        Triple: Pointer<Byte>,
    ): LLVMOrcObjectLayerRef

    public fun allocate(arena: Arena): MemorySegment =
        Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

    public companion object {
        @JvmStatic
        public val invokeHandle: MethodHandle =
            MethodHandles.lookup()
                .unreflect(LLVMOrcLLJITBuilderObjectLinkingLayerCreatorFunction::class.java.methods.find {
                    it.name == "invoke"
                }
                )

        @JvmStatic
        public val fd: FunctionDescriptor = FunctionDescriptor.of(
            `$RuntimeHelper`.POINTER,
            `$RuntimeHelper`.POINTER,
            `$RuntimeHelper`.POINTER,
            `$RuntimeHelper`.POINTER,
        )
    }
}
