// this file is auto generated by endoqa kotlin ffi, modify it with caution
package llvm.c.callback

import llvm.c.`$RuntimeHelper`
import llvm.c.LLVMOrcSymbolStringPoolEntryRef
import llvm.c.Pointer
import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles

public fun interface LLVMOrcSymbolPredicate {
    public fun invoke(Ctx: Pointer<Unit>, Sym: LLVMOrcSymbolStringPoolEntryRef): Int

    public fun allocate(arena: Arena): MemorySegment =
        Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

    public companion object {
        @JvmStatic
        public val invokeHandle: MethodHandle =
            MethodHandles.lookup().unreflect(LLVMOrcSymbolPredicate::class.java.methods.find {
                it.name == "invoke"
            }
            )

        @JvmStatic
        public val fd: FunctionDescriptor = FunctionDescriptor.of(
            ValueLayout.JAVA_INT,
            `$RuntimeHelper`.POINTER,
            `$RuntimeHelper`.POINTER,
        )
    }
}
