// this file is auto generated by endoqa kotlin ffi, modify it with caution
package llvm.c.callback

import llvm.c.`$RuntimeHelper`
import llvm.c.Pointer
import llvm.c.lto_codegen_diagnostic_severity_t
import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles

public fun interface lto_diagnostic_handler_t {
    public fun invoke(
        severity: lto_codegen_diagnostic_severity_t,
        diag: Pointer<Byte>,
        ctxt: Pointer<Unit>,
    )

    public fun allocate(arena: Arena): MemorySegment =
        Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

    public companion object {
        @JvmStatic
        public val invokeHandle: MethodHandle =
            MethodHandles.filterArguments(
                MethodHandles.lookup().unreflect(lto_diagnostic_handler_t::class.java.methods.find {
                    it.name == "invoke"
                }
                ),
                1, lto_codegen_diagnostic_severity_t.fromInt, null, null,
            )

        @JvmStatic
        public val fd: FunctionDescriptor = FunctionDescriptor.ofVoid(
            ValueLayout.JAVA_INT,
            `$RuntimeHelper`.POINTER,
            `$RuntimeHelper`.POINTER,
        )
    }
}
