// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

typealias CXVirtualFileOverlay = Pointer<CXVirtualFileOverlayImpl>

typealias CXModuleMapDescriptor = Pointer<CXModuleMapDescriptorImpl>

typealias CXFile = Pointer<Unit>

typealias CXDiagnostic = Pointer<Unit>

typealias CXDiagnosticSet = Pointer<Unit>

typealias CXIndex = Pointer<Unit>

typealias CXTargetInfo = Pointer<CXTargetInfoImpl>

typealias CXTranslationUnit = Pointer<CXTranslationUnitImpl>

typealias CXClientData = Pointer<Unit>


typealias CXCursorSet = Pointer<CXCursorSetImpl>

typealias CXCursorVisitor = Pointer<(
    cursor: CXCursor,
    parent: CXCursor,
    client_data: CXClientData,
) -> CXChildVisitResult>

typealias CXCursorVisitorBlock = Pointer<_CXChildVisitResult>

typealias CXPrintingPolicy = Pointer<Unit>

typealias CXModule = Pointer<Unit>

typealias CXCompletionString = Pointer<Unit>

typealias CXInclusionVisitor = Pointer<(
    included_file: CXFile,
    inclusion_stack: Pointer<CXSourceLocation>,
    include_len: UInt,
    client_data: CXClientData,
) -> Unit>

typealias CXEvalResult = Pointer<Unit>

typealias CXRemapping = Pointer<Unit>


typealias CXCursorAndRangeVisitorBlock = Pointer<_CXCursorAndRangeVisitorBlock>

typealias CXIdxClientFile = Pointer<Unit>

typealias CXIdxClientEntity = Pointer<Unit>

typealias CXIdxClientContainer = Pointer<Unit>

typealias CXIdxClientASTFile = Pointer<Unit>

typealias CXIndexAction = Pointer<Unit>

typealias CXFieldVisitor = Pointer<(
    C: CXCursor,
    client_data: CXClientData
) -> CXVisitorResult>
