// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

enum class CX_StorageClass(
    val `value`: Int,
) {
    Invalid(0x00000000),
    None(0x00000001),
    Extern(0x00000002),
    Static(0x00000003),
    PrivateExtern(0x00000004),
    OpenCLWorkGroupLocal(0x00000005),
    Auto(0x00000006),
    Register(0x00000007),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CX_StorageClass::class.java,
            "fromInt",
            MethodType.methodType(CX_StorageClass::class.java, Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CX_StorageClass::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: Int): CX_StorageClass = when (value) {
            0x00000000 -> Invalid
            0x00000001 -> None
            0x00000002 -> Extern
            0x00000003 -> Static
            0x00000004 -> PrivateExtern
            0x00000005 -> OpenCLWorkGroupLocal
            0x00000006 -> Auto
            0x00000007 -> Register
            else -> error("enum not found")
        }
    }
}
