// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

enum class CXAvailabilityKind(
    val `value`: Int,
) {
    Available(0x00000000),
    Deprecated(0x00000001),
    NotAvailable(0x00000002),
    NotAccessible(0x00000003),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXAvailabilityKind::class.java,
            "fromInt",
            MethodType.methodType(CXAvailabilityKind::class.java, Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXAvailabilityKind::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: Int): CXAvailabilityKind = when (value) {
            0x00000000 -> Available
            0x00000001 -> Deprecated
            0x00000002 -> NotAvailable
            0x00000003 -> NotAccessible
            else -> error("enum not found")
        }
    }
}
