// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

enum class CXCodeComplete_Flags(
    val `value`: Int,
) {
    IncludeMacros(0x00000001),
    IncludeCodePatterns(0x00000002),
    IncludeBriefComments(0x00000004),
    SkipPreamble(0x00000008),
    IncludeCompletionsWithFixIts(0x00000010),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXCodeComplete_Flags::class.java,
            "fromInt",
            MethodType.methodType(CXCodeComplete_Flags::class.java, Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXCodeComplete_Flags::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: Int): CXCodeComplete_Flags = when (value) {
            0x00000001 -> IncludeMacros
            0x00000002 -> IncludeCodePatterns
            0x00000004 -> IncludeBriefComments
            0x00000008 -> SkipPreamble
            0x00000010 -> IncludeCompletionsWithFixIts
            else -> error("enum not found")
        }
    }
}
