// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
value class CXCodeCompleteResults(
    val `$mem`: MemorySegment,
) {
    var Results: Pointer<CXCompletionResult>
        get() = ResultsHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            ResultsHandle.set(this.`$mem`, 0L, value)
        }

    var NumResults: UInt
        get() = (NumResultsHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            NumResultsHandle.set(this.`$mem`, 0L, value.toInt())
        }

    constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    companion object {
        val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("Results"),
            ValueLayout.JAVA_INT.withName("NumResults"),
            MemoryLayout.paddingLayout(4),
        ).withName("CXCodeCompleteResults")

        @JvmField
        val ResultsHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("Results"))

        @JvmField
        val NumResultsHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("NumResults"))

        @JvmStatic
        fun allocate(alloc: SegmentAllocator): CXCodeCompleteResults =
            CXCodeCompleteResults(alloc.allocate(layout))
    }
}
