// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.VarHandle

@JvmInline
value class CXCursorAndRangeVisitor(
    val `$mem`: MemorySegment,
) {
    var context: Pointer<Unit>
        get() = contextHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            contextHandle.set(this.`$mem`, 0L, value)
        }

    var visit: Pointer<(
        context: Pointer<Unit>,
        `$p1`: CXCursor,
        `$p2`: CXSourceRange,
    ) -> CXVisitorResult>
        get() = visitHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            visitHandle.set(this.`$mem`, 0L, value)
        }

    constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    companion object {
        val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("context"),
            `$RuntimeHelper`.POINTER.withName("visit"),
        ).withName("CXCursorAndRangeVisitor")

        @JvmField
        val contextHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("context"))

        @JvmField
        val visitHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("visit"))

        @JvmStatic
        fun allocate(alloc: SegmentAllocator): CXCursorAndRangeVisitor =
            CXCursorAndRangeVisitor(alloc.allocate(layout))

        fun interface visit {
            fun invoke(
                context: Pointer<Unit>,
                `$p1`: CXCursor,
                `$p2`: CXSourceRange,
            ): CXVisitorResult

            fun allocate(arena: Arena): MemorySegment =
                Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

            companion object {
                @JvmStatic
                val invokeHandle: MethodHandle =
                    MethodHandles.filterReturnValue(MethodHandles.lookup().unreflect(visit::class.java.methods.find {
                        it.name == "invoke"
                    }
                    ), CXVisitorResult.toInt)

                @JvmStatic
                val fd: FunctionDescriptor = FunctionDescriptor.of(
                    ValueLayout.JAVA_INT,
                    `$RuntimeHelper`.POINTER,
                    CXCursor.layout,
                    CXSourceRange.layout,
                )
            }
        }
    }
}
