// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

enum class CXErrorCode(
    val `value`: Int,
) {
    Success(0x00000000),
    Failure(0x00000001),
    Crashed(0x00000002),
    InvalidArguments(0x00000003),
    ASTReadError(0x00000004),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXErrorCode::class.java,
            "fromInt",
            MethodType.methodType(CXErrorCode::class.java, Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXErrorCode::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: Int): CXErrorCode = when (value) {
            0x00000000 -> Success
            0x00000001 -> Failure
            0x00000002 -> Crashed
            0x00000003 -> InvalidArguments
            0x00000004 -> ASTReadError
            else -> error("enum not found")
        }
    }
}
