// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

enum class CXIdxDeclInfoFlags(
    val `value`: Int,
) {
    CXIdxDeclFlag_Skipped(0x00000001),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXIdxDeclInfoFlags::class.java,
            "fromInt",
            MethodType.methodType(CXIdxDeclInfoFlags::class.java, Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXIdxDeclInfoFlags::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: Int): CXIdxDeclInfoFlags = when (value) {
            0x00000001 -> CXIdxDeclFlag_Skipped
            else -> error("enum not found")
        }
    }
}
