// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

@JvmInline
value class CXIdxEntityRefInfo(
    val `$mem`: MemorySegment,
) {
    var kind: CXIdxEntityRefKind
        get() = CXIdxEntityRefKind.fromInt(kindHandle.get(this.`$mem`, 0L) as Int)
        set(`value`) {
            kindHandle.set(this.`$mem`, 0L, value.value)
        }

    var cursor: CXCursor
        get() = CXCursor(cursorHandle.invokeExact(this.`$mem`, 0L) as MemorySegment)
        set(`value`) {
            MemorySegment.copy(value.`$mem`, 0L, this.cursor.`$mem`, 0L, CXCursor.layout.byteSize())
        }

    var loc: CXIdxLoc
        get() = CXIdxLoc(locHandle.invokeExact(this.`$mem`, 0L) as MemorySegment)
        set(`value`) {
            MemorySegment.copy(value.`$mem`, 0L, this.loc.`$mem`, 0L, CXIdxLoc.layout.byteSize())
        }

    var referencedEntity: Pointer<CXIdxEntityInfo>
        get() = referencedEntityHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            referencedEntityHandle.set(this.`$mem`, 0L, value)
        }

    var parentEntity: Pointer<CXIdxEntityInfo>
        get() = parentEntityHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            parentEntityHandle.set(this.`$mem`, 0L, value)
        }

    var container: Pointer<CXIdxContainerInfo>
        get() = containerHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            containerHandle.set(this.`$mem`, 0L, value)
        }

    var role: CXSymbolRole
        get() = CXSymbolRole.fromInt(roleHandle.get(this.`$mem`, 0L) as Int)
        set(`value`) {
            roleHandle.set(this.`$mem`, 0L, value.value)
        }

    constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    companion object {
        val layout: StructLayout = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("kind"),
            CXCursor.layout.withName("cursor"),
            MemoryLayout.paddingLayout(4),
            CXIdxLoc.layout.withName("loc"),
            `$RuntimeHelper`.POINTER.withName("referencedEntity"),
            `$RuntimeHelper`.POINTER.withName("parentEntity"),
            `$RuntimeHelper`.POINTER.withName("container"),
            ValueLayout.JAVA_INT.withName("role"),
            MemoryLayout.paddingLayout(4),
        ).withName("CXIdxEntityRefInfo")

        @JvmField
        val kindHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("kind"))

        @JvmField
        val cursorHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("cursor"))

        @JvmField
        val locHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("loc"))

        @JvmField
        val referencedEntityHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("referencedEntity"))

        @JvmField
        val parentEntityHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("parentEntity"))

        @JvmField
        val containerHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("container"))

        @JvmField
        val roleHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("role"))

        @JvmStatic
        fun allocate(alloc: SegmentAllocator): CXIdxEntityRefInfo =
            CXIdxEntityRefInfo(alloc.allocate(layout))
    }
}
