// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

enum class CXLinkageKind(
    val `value`: Int,
) {
    Invalid(0x00000000),
    NoLinkage(0x00000001),
    Internal(0x00000002),
    UniqueExternal(0x00000003),
    External(0x00000004),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXLinkageKind::class.java,
            "fromInt",
            MethodType.methodType(CXLinkageKind::class.java, Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXLinkageKind::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: Int): CXLinkageKind = when (value) {
            0x00000000 -> Invalid
            0x00000001 -> NoLinkage
            0x00000002 -> Internal
            0x00000003 -> UniqueExternal
            0x00000004 -> External
            else -> error("enum not found")
        }
    }
}
