// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

enum class CXRefQualifierKind(
    val `value`: Int,
) {
    None(0x00000000),
    LValue(0x00000001),
    RValue(0x00000002),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXRefQualifierKind::class.java,
            "fromInt",
            MethodType.methodType(CXRefQualifierKind::class.java, Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXRefQualifierKind::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: Int): CXRefQualifierKind = when (value) {
            0x00000000 -> None
            0x00000001 -> LValue
            0x00000002 -> RValue
            else -> error("enum not found")
        }
    }
}
