// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

enum class CXSaveTranslationUnit_Flags(
    val `value`: Int,
) {
    CXSaveTranslationUnit_None(0x00000000),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXSaveTranslationUnit_Flags::class.java,
            "fromInt",
            MethodType.methodType(CXSaveTranslationUnit_Flags::class.java, Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXSaveTranslationUnit_Flags::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: Int): CXSaveTranslationUnit_Flags = when (value) {
            0x00000000 -> CXSaveTranslationUnit_None
            else -> error("enum not found")
        }
    }
}
