// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

enum class CXSymbolRole(
    val `value`: Int,
) {
    None(0x00000000),
    Declaration(0x00000001),
    Definition(0x00000002),
    Reference(0x00000004),
    Read(0x00000008),
    Write(0x00000010),
    Call(0x00000020),
    Dynamic(0x00000040),
    AddressOf(0x00000080),
    Implicit(0x00000100),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXSymbolRole::class.java,
            "fromInt",
            MethodType.methodType(CXSymbolRole::class.java, Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXSymbolRole::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: Int): CXSymbolRole = when (value) {
            0x00000000 -> None
            0x00000001 -> Declaration
            0x00000002 -> Definition
            0x00000004 -> Reference
            0x00000008 -> Read
            0x00000010 -> Write
            0x00000020 -> Call
            0x00000040 -> Dynamic
            0x00000080 -> AddressOf
            0x00000100 -> Implicit
            else -> error("enum not found")
        }
    }
}
