// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

enum class CXTemplateArgumentKind(
    val `value`: Int,
) {
    Null(0x00000000),
    Type(0x00000001),
    Declaration(0x00000002),
    NullPtr(0x00000003),
    Integral(0x00000004),
    Template(0x00000005),
    TemplateExpansion(0x00000006),
    Expression(0x00000007),
    Pack(0x00000008),
    Invalid(0x00000009),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXTemplateArgumentKind::class.java,
            "fromInt",
            MethodType.methodType(CXTemplateArgumentKind::class.java, Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXTemplateArgumentKind::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: Int): CXTemplateArgumentKind = when (value) {
            0x00000000 -> Null
            0x00000001 -> Type
            0x00000002 -> Declaration
            0x00000003 -> NullPtr
            0x00000004 -> Integral
            0x00000005 -> Template
            0x00000006 -> TemplateExpansion
            0x00000007 -> Expression
            0x00000008 -> Pack
            0x00000009 -> Invalid
            else -> error("enum not found")
        }
    }
}
