// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
value class CXTUResourceUsage(
    val `$mem`: MemorySegment,
) {
    var `data`: Pointer<Unit>
        get() = dataHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            dataHandle.set(this.`$mem`, 0L, value)
        }

    var numEntries: UInt
        get() = (numEntriesHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            numEntriesHandle.set(this.`$mem`, 0L, value.toInt())
        }

    var entries: Pointer<CXTUResourceUsageEntry>
        get() = entriesHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            entriesHandle.set(this.`$mem`, 0L, value)
        }

    constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    companion object {
        val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("data"),
            ValueLayout.JAVA_INT.withName("numEntries"),
            MemoryLayout.paddingLayout(4),
            `$RuntimeHelper`.POINTER.withName("entries"),
        ).withName("CXTUResourceUsage")

        @JvmField
        val dataHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("data"))

        @JvmField
        val numEntriesHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("numEntries"))

        @JvmField
        val entriesHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("entries"))

        @JvmStatic
        fun allocate(alloc: SegmentAllocator): CXTUResourceUsage =
            CXTUResourceUsage(alloc.allocate(layout))
    }
}
