// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType

enum class CXTypeKind(
    val `value`: kotlin.Int,
) {
    Invalid(0x00000000),
    Unexposed(0x00000001),
    Void(0x00000002),
    Bool(0x00000003),
    Char_U(0x00000004),
    UChar(0x00000005),
    Char16(0x00000006),
    Char32(0x00000007),
    UShort(0x00000008),
    UInt(0x00000009),
    ULong(0x0000000a),
    ULongLong(0x0000000b),
    UInt128(0x0000000c),
    Char_S(0x0000000d),
    SChar(0x0000000e),
    WChar(0x0000000f),
    Short(0x00000010),
    Int(0x00000011),
    Long(0x00000012),
    LongLong(0x00000013),
    Int128(0x00000014),
    Float(0x00000015),
    Double(0x00000016),
    LongDouble(0x00000017),
    NullPtr(0x00000018),
    Overload(0x00000019),
    Dependent(0x0000001a),
    ObjCId(0x0000001b),
    ObjCClass(0x0000001c),
    ObjCSel(0x0000001d),
    Float128(0x0000001e),
    Half(0x0000001f),
    Float16(0x00000020),
    ShortAccum(0x00000021),
    Accum(0x00000022),
    LongAccum(0x00000023),
    UShortAccum(0x00000024),
    UAccum(0x00000025),
    ULongAccum(0x00000026),
    BFloat16(0x00000027),
    Ibm128(0x00000028),
    FirstBuiltin(0x00000002),
    LastBuiltin(0x00000028),
    Complex(0x00000064),
    Pointer(0x00000065),
    BlockPointer(0x00000066),
    LValueReference(0x00000067),
    RValueReference(0x00000068),
    Record(0x00000069),
    Enum(0x0000006a),
    Typedef(0x0000006b),
    ObjCInterface(0x0000006c),
    ObjCObjectPointer(0x0000006d),
    FunctionNoProto(0x0000006e),
    FunctionProto(0x0000006f),
    ConstantArray(0x00000070),
    Vector(0x00000071),
    IncompleteArray(0x00000072),
    VariableArray(0x00000073),
    DependentSizedArray(0x00000074),
    MemberPointer(0x00000075),
    Auto(0x00000076),
    Elaborated(0x00000077),
    Pipe(0x00000078),
    OCLImage1dRO(0x00000079),
    OCLImage1dArrayRO(0x0000007a),
    OCLImage1dBufferRO(0x0000007b),
    OCLImage2dRO(0x0000007c),
    OCLImage2dArrayRO(0x0000007d),
    OCLImage2dDepthRO(0x0000007e),
    OCLImage2dArrayDepthRO(0x0000007f),
    OCLImage2dMSAARO(0x00000080),
    OCLImage2dArrayMSAARO(0x00000081),
    OCLImage2dMSAADepthRO(0x00000082),
    OCLImage2dArrayMSAADepthRO(0x00000083),
    OCLImage3dRO(0x00000084),
    OCLImage1dWO(0x00000085),
    OCLImage1dArrayWO(0x00000086),
    OCLImage1dBufferWO(0x00000087),
    OCLImage2dWO(0x00000088),
    OCLImage2dArrayWO(0x00000089),
    OCLImage2dDepthWO(0x0000008a),
    OCLImage2dArrayDepthWO(0x0000008b),
    OCLImage2dMSAAWO(0x0000008c),
    OCLImage2dArrayMSAAWO(0x0000008d),
    OCLImage2dMSAADepthWO(0x0000008e),
    OCLImage2dArrayMSAADepthWO(0x0000008f),
    OCLImage3dWO(0x00000090),
    OCLImage1dRW(0x00000091),
    OCLImage1dArrayRW(0x00000092),
    OCLImage1dBufferRW(0x00000093),
    OCLImage2dRW(0x00000094),
    OCLImage2dArrayRW(0x00000095),
    OCLImage2dDepthRW(0x00000096),
    OCLImage2dArrayDepthRW(0x00000097),
    OCLImage2dMSAARW(0x00000098),
    OCLImage2dArrayMSAARW(0x00000099),
    OCLImage2dMSAADepthRW(0x0000009a),
    OCLImage2dArrayMSAADepthRW(0x0000009b),
    OCLImage3dRW(0x0000009c),
    OCLSampler(0x0000009d),
    OCLEvent(0x0000009e),
    OCLQueue(0x0000009f),
    OCLReserveID(0x000000a0),
    ObjCObject(0x000000a1),
    ObjCTypeParam(0x000000a2),
    Attributed(0x000000a3),
    OCLIntelSubgroupAVCMcePayload(0x000000a4),
    OCLIntelSubgroupAVCImePayload(0x000000a5),
    OCLIntelSubgroupAVCRefPayload(0x000000a6),
    OCLIntelSubgroupAVCSicPayload(0x000000a7),
    OCLIntelSubgroupAVCMceResult(0x000000a8),
    OCLIntelSubgroupAVCImeResult(0x000000a9),
    OCLIntelSubgroupAVCRefResult(0x000000aa),
    OCLIntelSubgroupAVCSicResult(0x000000ab),
    OCLIntelSubgroupAVCImeResultSingleReferenceStreamout(0x000000ac),
    OCLIntelSubgroupAVCImeResultDualReferenceStreamout(0x000000ad),
    OCLIntelSubgroupAVCImeSingleReferenceStreamin(0x000000ae),
    OCLIntelSubgroupAVCImeDualReferenceStreamin(0x000000af),
    OCLIntelSubgroupAVCImeResultSingleRefStreamout(0x000000ac),
    OCLIntelSubgroupAVCImeResultDualRefStreamout(0x000000ad),
    OCLIntelSubgroupAVCImeSingleRefStreamin(0x000000ae),
    OCLIntelSubgroupAVCImeDualRefStreamin(0x000000af),
    ExtVector(0x000000b0),
    Atomic(0x000000b1),
    BTFTagAttributed(0x000000b2),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXTypeKind::class.java,
            "fromInt",
            MethodType.methodType(CXTypeKind::class.java, kotlin.Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXTypeKind::class.java,
            "value",
            kotlin.Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: kotlin.Int): CXTypeKind = when (value) {
            0x00000000 -> Invalid
            0x00000001 -> Unexposed
            0x00000002 -> Void
            0x00000003 -> Bool
            0x00000004 -> Char_U
            0x00000005 -> UChar
            0x00000006 -> Char16
            0x00000007 -> Char32
            0x00000008 -> UShort
            0x00000009 -> UInt
            0x0000000a -> ULong
            0x0000000b -> ULongLong
            0x0000000c -> UInt128
            0x0000000d -> Char_S
            0x0000000e -> SChar
            0x0000000f -> WChar
            0x00000010 -> Short
            0x00000011 -> Int
            0x00000012 -> Long
            0x00000013 -> LongLong
            0x00000014 -> Int128
            0x00000015 -> Float
            0x00000016 -> Double
            0x00000017 -> LongDouble
            0x00000018 -> NullPtr
            0x00000019 -> Overload
            0x0000001a -> Dependent
            0x0000001b -> ObjCId
            0x0000001c -> ObjCClass
            0x0000001d -> ObjCSel
            0x0000001e -> Float128
            0x0000001f -> Half
            0x00000020 -> Float16
            0x00000021 -> ShortAccum
            0x00000022 -> Accum
            0x00000023 -> LongAccum
            0x00000024 -> UShortAccum
            0x00000025 -> UAccum
            0x00000026 -> ULongAccum
            0x00000027 -> BFloat16
            0x00000028 -> Ibm128
            0x00000002 -> FirstBuiltin
            0x00000028 -> LastBuiltin
            0x00000064 -> Complex
            0x00000065 -> Pointer
            0x00000066 -> BlockPointer
            0x00000067 -> LValueReference
            0x00000068 -> RValueReference
            0x00000069 -> Record
            0x0000006a -> Enum
            0x0000006b -> Typedef
            0x0000006c -> ObjCInterface
            0x0000006d -> ObjCObjectPointer
            0x0000006e -> FunctionNoProto
            0x0000006f -> FunctionProto
            0x00000070 -> ConstantArray
            0x00000071 -> Vector
            0x00000072 -> IncompleteArray
            0x00000073 -> VariableArray
            0x00000074 -> DependentSizedArray
            0x00000075 -> MemberPointer
            0x00000076 -> Auto
            0x00000077 -> Elaborated
            0x00000078 -> Pipe
            0x00000079 -> OCLImage1dRO
            0x0000007a -> OCLImage1dArrayRO
            0x0000007b -> OCLImage1dBufferRO
            0x0000007c -> OCLImage2dRO
            0x0000007d -> OCLImage2dArrayRO
            0x0000007e -> OCLImage2dDepthRO
            0x0000007f -> OCLImage2dArrayDepthRO
            0x00000080 -> OCLImage2dMSAARO
            0x00000081 -> OCLImage2dArrayMSAARO
            0x00000082 -> OCLImage2dMSAADepthRO
            0x00000083 -> OCLImage2dArrayMSAADepthRO
            0x00000084 -> OCLImage3dRO
            0x00000085 -> OCLImage1dWO
            0x00000086 -> OCLImage1dArrayWO
            0x00000087 -> OCLImage1dBufferWO
            0x00000088 -> OCLImage2dWO
            0x00000089 -> OCLImage2dArrayWO
            0x0000008a -> OCLImage2dDepthWO
            0x0000008b -> OCLImage2dArrayDepthWO
            0x0000008c -> OCLImage2dMSAAWO
            0x0000008d -> OCLImage2dArrayMSAAWO
            0x0000008e -> OCLImage2dMSAADepthWO
            0x0000008f -> OCLImage2dArrayMSAADepthWO
            0x00000090 -> OCLImage3dWO
            0x00000091 -> OCLImage1dRW
            0x00000092 -> OCLImage1dArrayRW
            0x00000093 -> OCLImage1dBufferRW
            0x00000094 -> OCLImage2dRW
            0x00000095 -> OCLImage2dArrayRW
            0x00000096 -> OCLImage2dDepthRW
            0x00000097 -> OCLImage2dArrayDepthRW
            0x00000098 -> OCLImage2dMSAARW
            0x00000099 -> OCLImage2dArrayMSAARW
            0x0000009a -> OCLImage2dMSAADepthRW
            0x0000009b -> OCLImage2dArrayMSAADepthRW
            0x0000009c -> OCLImage3dRW
            0x0000009d -> OCLSampler
            0x0000009e -> OCLEvent
            0x0000009f -> OCLQueue
            0x000000a0 -> OCLReserveID
            0x000000a1 -> ObjCObject
            0x000000a2 -> ObjCTypeParam
            0x000000a3 -> Attributed
            0x000000a4 -> OCLIntelSubgroupAVCMcePayload
            0x000000a5 -> OCLIntelSubgroupAVCImePayload
            0x000000a6 -> OCLIntelSubgroupAVCRefPayload
            0x000000a7 -> OCLIntelSubgroupAVCSicPayload
            0x000000a8 -> OCLIntelSubgroupAVCMceResult
            0x000000a9 -> OCLIntelSubgroupAVCImeResult
            0x000000aa -> OCLIntelSubgroupAVCRefResult
            0x000000ab -> OCLIntelSubgroupAVCSicResult
            0x000000ac -> OCLIntelSubgroupAVCImeResultSingleReferenceStreamout
            0x000000ad -> OCLIntelSubgroupAVCImeResultDualReferenceStreamout
            0x000000ae -> OCLIntelSubgroupAVCImeSingleReferenceStreamin
            0x000000af -> OCLIntelSubgroupAVCImeDualReferenceStreamin
            0x000000ac -> OCLIntelSubgroupAVCImeResultSingleRefStreamout
            0x000000ad -> OCLIntelSubgroupAVCImeResultDualRefStreamout
            0x000000ae -> OCLIntelSubgroupAVCImeSingleRefStreamin
            0x000000af -> OCLIntelSubgroupAVCImeDualRefStreamin
            0x000000b0 -> ExtVector
            0x000000b1 -> Atomic
            0x000000b2 -> BTFTagAttributed
            else -> error("enum not found")
        }
    }
}
