// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.llvm.proc

import java.lang.foreign.Arena
import java.lang.foreign.FunctionDescriptor
import java.lang.foreign.Linker
import java.lang.foreign.MemorySegment
import java.lang.foreign.ValueLayout
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import kotlin.Byte
import kotlin.Unit
import kotlin.jvm.JvmStatic
import lib.llvm.Pointer
import lib.llvm.`$RuntimeHelper`
import lib.llvm.lto_codegen_diagnostic_severity_t

public fun interface lto_diagnostic_handler_t {
  public fun invoke(
    severity: lto_codegen_diagnostic_severity_t,
    diag: Pointer<Byte>,
    ctxt: Pointer<Unit>,
  )

  public fun allocate(arena: Arena): MemorySegment =
      Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

  public companion object {
    @JvmStatic
    public val invokeHandle: MethodHandle =
        MethodHandles.filterArguments(MethodHandles.lookup().unreflect(lto_diagnostic_handler_t::class.java.methods.find {
          it.name == "invoke"}
        ), 1,lto_codegen_diagnostic_severity_t.fromInt,null,null,)

    @JvmStatic
    public val fd: FunctionDescriptor = FunctionDescriptor.ofVoid(
      ValueLayout.JAVA_INT,
      `$RuntimeHelper`.POINTER,
      `$RuntimeHelper`.POINTER,
    )
  }
}
