// this file is auto generated by endoqa kotlin ffi, modify it with caution
package llvm.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class LLVMIntPredicate(
    public val `value`: Int,
) {
    EQ(32),
    NE(33),
    UGT(34),
    UGE(35),
    ULT(36),
    ULE(37),
    SGT(38),
    SGE(39),
    SLT(40),
    SLE(41),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            LLVMIntPredicate::class.java,
            "fromInt",
            MethodType.methodType(LLVMIntPredicate::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            LLVMIntPredicate::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): LLVMIntPredicate = when (value) {
            EQ.value -> EQ
            NE.value -> NE
            UGT.value -> UGT
            UGE.value -> UGE
            ULT.value -> ULT
            ULE.value -> ULE
            SGT.value -> SGT
            SGE.value -> SGE
            SLT.value -> SLT
            SLE.value -> SLE
            else -> error("enum not found")
        }
    }
}
