// this file is auto generated by endoqa kotlin ffi, modify it with caution
package llvm.c

import java.lang.foreign.*

@JvmInline
public value class LLVMOpaqueExecutionEngine(
    public val `$mem`: MemorySegment,
) {
    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(LLVMOpaqueExecutionEngine.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
        ).withName("LLVMOpaqueExecutionEngine")

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): LLVMOpaqueExecutionEngine =
            LLVMOpaqueExecutionEngine(alloc.allocate(LLVMOpaqueExecutionEngine.layout))
    }
}
