// this file is auto generated by endoqa kotlin ffi, modify it with caution
package llvm.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class LLVMTailCallKind(
    public val `value`: Int,
) {
    None(0),
    Tail(1),
    MustTail(2),
    NoTail(3),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            LLVMTailCallKind::class.java,
            "fromInt",
            MethodType.methodType(LLVMTailCallKind::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            LLVMTailCallKind::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): LLVMTailCallKind = when (value) {
            None.value -> None
            Tail.value -> Tail
            MustTail.value -> MustTail
            NoTail.value -> NoTail
            else -> error("enum not found")
        }
    }
}
