// this file is auto generated by endoqa kotlin ffi, modify it with caution
package llvm.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class LLVMTypeKind(
    public val `value`: Int,
) {
    VoidTypeKind(0),
    HalfTypeKind(1),
    FloatTypeKind(2),
    DoubleTypeKind(3),
    X86_FP80TypeKind(4),
    FP128TypeKind(5),
    PPC_FP128TypeKind(6),
    LabelTypeKind(7),
    IntegerTypeKind(8),
    FunctionTypeKind(9),
    StructTypeKind(10),
    ArrayTypeKind(11),
    PointerTypeKind(12),
    VectorTypeKind(13),
    MetadataTypeKind(14),
    X86_MMXTypeKind(15),
    TokenTypeKind(16),
    ScalableVectorTypeKind(17),
    BFloatTypeKind(18),
    X86_AMXTypeKind(19),
    TargetExtTypeKind(20),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            LLVMTypeKind::class.java,
            "fromInt",
            MethodType.methodType(LLVMTypeKind::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            LLVMTypeKind::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): LLVMTypeKind = when (value) {
            VoidTypeKind.value -> VoidTypeKind
            HalfTypeKind.value -> HalfTypeKind
            FloatTypeKind.value -> FloatTypeKind
            DoubleTypeKind.value -> DoubleTypeKind
            X86_FP80TypeKind.value -> X86_FP80TypeKind
            FP128TypeKind.value -> FP128TypeKind
            PPC_FP128TypeKind.value -> PPC_FP128TypeKind
            LabelTypeKind.value -> LabelTypeKind
            IntegerTypeKind.value -> IntegerTypeKind
            FunctionTypeKind.value -> FunctionTypeKind
            StructTypeKind.value -> StructTypeKind
            ArrayTypeKind.value -> ArrayTypeKind
            PointerTypeKind.value -> PointerTypeKind
            VectorTypeKind.value -> VectorTypeKind
            MetadataTypeKind.value -> MetadataTypeKind
            X86_MMXTypeKind.value -> X86_MMXTypeKind
            TokenTypeKind.value -> TokenTypeKind
            ScalableVectorTypeKind.value -> ScalableVectorTypeKind
            BFloatTypeKind.value -> BFloatTypeKind
            X86_AMXTypeKind.value -> X86_AMXTypeKind
            TargetExtTypeKind.value -> TargetExtTypeKind
            else -> error("enum not found")
        }
    }
}
