// this file is auto generated by endoqa kotlin ffi, modify it with caution
package llvm.c

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

@JvmInline
public value class LLVMOrcCSymbolAliasMapPair(
    public val `$mem`: MemorySegment,
) {
    public var Name: LLVMOrcSymbolStringPoolEntryRef
        get() = LLVMOrcCSymbolAliasMapPair.NameHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            LLVMOrcCSymbolAliasMapPair.NameHandle.set(this.`$mem`, 0L, value)
        }

    public var Entry: LLVMOrcCSymbolAliasMapEntry
        get() =
            LLVMOrcCSymbolAliasMapEntry(
                LLVMOrcCSymbolAliasMapPair.EntryHandle.invokeExact(
                    this.`$mem`,
                    0L
                ) as MemorySegment
            )
        set(`value`) {
            MemorySegment.copy(
                value.`$mem`, 0L, this.Entry.`$mem`, 0L,
                LLVMOrcCSymbolAliasMapEntry.layout.byteSize()
            )
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(LLVMOrcCSymbolAliasMapPair.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("Name"),
            LLVMOrcCSymbolAliasMapEntry.layout.withName("Entry"),
        ).withName("LLVMOrcCSymbolAliasMapPair")

        @JvmField
        public val NameHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("Name"))

        @JvmField
        public val EntryHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("Entry"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): LLVMOrcCSymbolAliasMapPair =
            LLVMOrcCSymbolAliasMapPair(alloc.allocate(LLVMOrcCSymbolAliasMapPair.layout))
    }
}
