// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

enum class CX_CXXAccessSpecifier(
    val `value`: Int,
) {
    InvalidAccessSpecifier(0x00000000),
    Public(0x00000001),
    Protected(0x00000002),
    Private(0x00000003),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CX_CXXAccessSpecifier::class.java,
            "fromInt",
            MethodType.methodType(CX_CXXAccessSpecifier::class.java, Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CX_CXXAccessSpecifier::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: Int): CX_CXXAccessSpecifier = when (value) {
            0x00000000 -> InvalidAccessSpecifier
            0x00000001 -> Public
            0x00000002 -> Protected
            0x00000003 -> Private
            else -> error("enum not found")
        }
    }
}
