// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

@JvmInline
value class CXCursor(
    val `$mem`: MemorySegment,
) {
    var kind: CXCursorKind
        get() = CXCursorKind.fromInt(kindHandle.get(this.`$mem`, 0L) as Int)
        set(`value`) {
            kindHandle.set(this.`$mem`, 0L, value.value)
        }

    var xdata: Int
        get() = xdataHandle.get(this.`$mem`, 0L) as Int
        set(`value`) {
            xdataHandle.set(this.`$mem`, 0L, value)
        }

    val `data`: NativeArray<Pointer<Unit>>
        get() = dataHandle.invokeExact(this.`$mem`, 0L) as MemorySegment

    constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    companion object {
        val layout: StructLayout = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("kind"),
            ValueLayout.JAVA_INT.withName("xdata"),
            MemoryLayout.sequenceLayout(3L, `$RuntimeHelper`.POINTER).withName("data"),
        ).withName("CXCursor")

        @JvmField
        val kindHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("kind"))

        @JvmField
        val xdataHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("xdata"))

        @JvmField
        val dataHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("data"))

        @JvmStatic
        fun allocate(alloc: SegmentAllocator): CXCursor =
            CXCursor(alloc.allocate(layout))
    }
}
