// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

enum class CXCursorKind(
    val `value`: Int,
) {
    UnexposedDecl(0x00000001),
    StructDecl(0x00000002),
    UnionDecl(0x00000003),
    ClassDecl(0x00000004),
    EnumDecl(0x00000005),
    FieldDecl(0x00000006),
    EnumConstantDecl(0x00000007),
    FunctionDecl(0x00000008),
    VarDecl(0x00000009),
    ParmDecl(0x0000000a),
    ObjCInterfaceDecl(0x0000000b),
    ObjCCategoryDecl(0x0000000c),
    ObjCProtocolDecl(0x0000000d),
    ObjCPropertyDecl(0x0000000e),
    ObjCIvarDecl(0x0000000f),
    ObjCInstanceMethodDecl(0x00000010),
    ObjCClassMethodDecl(0x00000011),
    ObjCImplementationDecl(0x00000012),
    ObjCCategoryImplDecl(0x00000013),
    TypedefDecl(0x00000014),
    CXXMethod(0x00000015),
    Namespace(0x00000016),
    LinkageSpec(0x00000017),
    Constructor(0x00000018),
    Destructor(0x00000019),
    ConversionFunction(0x0000001a),
    TemplateTypeParameter(0x0000001b),
    NonTypeTemplateParameter(0x0000001c),
    TemplateTemplateParameter(0x0000001d),
    FunctionTemplate(0x0000001e),
    ClassTemplate(0x0000001f),
    ClassTemplatePartialSpecialization(0x00000020),
    NamespaceAlias(0x00000021),
    UsingDirective(0x00000022),
    UsingDeclaration(0x00000023),
    TypeAliasDecl(0x00000024),
    ObjCSynthesizeDecl(0x00000025),
    ObjCDynamicDecl(0x00000026),
    CXXAccessSpecifier(0x00000027),
    FirstDecl(0x00000001),
    LastDecl(0x00000027),
    FirstRef(0x00000028),
    ObjCSuperClassRef(0x00000028),
    ObjCProtocolRef(0x00000029),
    ObjCClassRef(0x0000002a),
    TypeRef(0x0000002b),
    CXXBaseSpecifier(0x0000002c),
    TemplateRef(0x0000002d),
    NamespaceRef(0x0000002e),
    MemberRef(0x0000002f),
    LabelRef(0x00000030),
    OverloadedDeclRef(0x00000031),
    VariableRef(0x00000032),
    LastRef(0x00000032),
    FirstInvalid(0x00000046),
    InvalidFile(0x00000046),
    NoDeclFound(0x00000047),
    NotImplemented(0x00000048),
    InvalidCode(0x00000049),
    LastInvalid(0x00000049),
    FirstExpr(0x00000064),
    UnexposedExpr(0x00000064),
    DeclRefExpr(0x00000065),
    MemberRefExpr(0x00000066),
    CallExpr(0x00000067),
    ObjCMessageExpr(0x00000068),
    BlockExpr(0x00000069),
    IntegerLiteral(0x0000006a),
    FloatingLiteral(0x0000006b),
    ImaginaryLiteral(0x0000006c),
    StringLiteral(0x0000006d),
    CharacterLiteral(0x0000006e),
    ParenExpr(0x0000006f),
    UnaryOperator(0x00000070),
    ArraySubscriptExpr(0x00000071),
    BinaryOperator(0x00000072),
    CompoundAssignOperator(0x00000073),
    ConditionalOperator(0x00000074),
    CStyleCastExpr(0x00000075),
    CompoundLiteralExpr(0x00000076),
    InitListExpr(0x00000077),
    AddrLabelExpr(0x00000078),
    StmtExpr(0x00000079),
    GenericSelectionExpr(0x0000007a),
    GNUNullExpr(0x0000007b),
    CXXStaticCastExpr(0x0000007c),
    CXXDynamicCastExpr(0x0000007d),
    CXXReinterpretCastExpr(0x0000007e),
    CXXConstCastExpr(0x0000007f),
    CXXFunctionalCastExpr(0x00000080),
    CXXTypeidExpr(0x00000081),
    CXXBoolLiteralExpr(0x00000082),
    CXXNullPtrLiteralExpr(0x00000083),
    CXXThisExpr(0x00000084),
    CXXThrowExpr(0x00000085),
    CXXNewExpr(0x00000086),
    CXXDeleteExpr(0x00000087),
    UnaryExpr(0x00000088),
    ObjCStringLiteral(0x00000089),
    ObjCEncodeExpr(0x0000008a),
    ObjCSelectorExpr(0x0000008b),
    ObjCProtocolExpr(0x0000008c),
    ObjCBridgedCastExpr(0x0000008d),
    PackExpansionExpr(0x0000008e),
    SizeOfPackExpr(0x0000008f),
    LambdaExpr(0x00000090),
    ObjCBoolLiteralExpr(0x00000091),
    ObjCSelfExpr(0x00000092),
    OMPArraySectionExpr(0x00000093),
    ObjCAvailabilityCheckExpr(0x00000094),
    FixedPointLiteral(0x00000095),
    OMPArrayShapingExpr(0x00000096),
    OMPIteratorExpr(0x00000097),
    CXXAddrspaceCastExpr(0x00000098),
    ConceptSpecializationExpr(0x00000099),
    RequiresExpr(0x0000009a),
    CXXParenListInitExpr(0x0000009b),
    LastExpr(0x0000009b),
    FirstStmt(0x000000c8),
    UnexposedStmt(0x000000c8),
    LabelStmt(0x000000c9),
    CompoundStmt(0x000000ca),
    CaseStmt(0x000000cb),
    DefaultStmt(0x000000cc),
    IfStmt(0x000000cd),
    SwitchStmt(0x000000ce),
    WhileStmt(0x000000cf),
    DoStmt(0x000000d0),
    ForStmt(0x000000d1),
    GotoStmt(0x000000d2),
    IndirectGotoStmt(0x000000d3),
    ContinueStmt(0x000000d4),
    BreakStmt(0x000000d5),
    ReturnStmt(0x000000d6),
    GCCAsmStmt(0x000000d7),
    AsmStmt(0x000000d7),
    ObjCAtTryStmt(0x000000d8),
    ObjCAtCatchStmt(0x000000d9),
    ObjCAtFinallyStmt(0x000000da),
    ObjCAtThrowStmt(0x000000db),
    ObjCAtSynchronizedStmt(0x000000dc),
    ObjCAutoreleasePoolStmt(0x000000dd),
    ObjCForCollectionStmt(0x000000de),
    CXXCatchStmt(0x000000df),
    CXXTryStmt(0x000000e0),
    CXXForRangeStmt(0x000000e1),
    SEHTryStmt(0x000000e2),
    SEHExceptStmt(0x000000e3),
    SEHFinallyStmt(0x000000e4),
    MSAsmStmt(0x000000e5),
    NullStmt(0x000000e6),
    DeclStmt(0x000000e7),
    OMPParallelDirective(0x000000e8),
    OMPSimdDirective(0x000000e9),
    OMPForDirective(0x000000ea),
    OMPSectionsDirective(0x000000eb),
    OMPSectionDirective(0x000000ec),
    OMPSingleDirective(0x000000ed),
    OMPParallelForDirective(0x000000ee),
    OMPParallelSectionsDirective(0x000000ef),
    OMPTaskDirective(0x000000f0),
    OMPMasterDirective(0x000000f1),
    OMPCriticalDirective(0x000000f2),
    OMPTaskyieldDirective(0x000000f3),
    OMPBarrierDirective(0x000000f4),
    OMPTaskwaitDirective(0x000000f5),
    OMPFlushDirective(0x000000f6),
    SEHLeaveStmt(0x000000f7),
    OMPOrderedDirective(0x000000f8),
    OMPAtomicDirective(0x000000f9),
    OMPForSimdDirective(0x000000fa),
    OMPParallelForSimdDirective(0x000000fb),
    OMPTargetDirective(0x000000fc),
    OMPTeamsDirective(0x000000fd),
    OMPTaskgroupDirective(0x000000fe),
    OMPCancellationPointDirective(0x000000ff),
    OMPCancelDirective(0x00000100),
    OMPTargetDataDirective(0x00000101),
    OMPTaskLoopDirective(0x00000102),
    OMPTaskLoopSimdDirective(0x00000103),
    OMPDistributeDirective(0x00000104),
    OMPTargetEnterDataDirective(0x00000105),
    OMPTargetExitDataDirective(0x00000106),
    OMPTargetParallelDirective(0x00000107),
    OMPTargetParallelForDirective(0x00000108),
    OMPTargetUpdateDirective(0x00000109),
    OMPDistributeParallelForDirective(0x0000010a),
    OMPDistributeParallelForSimdDirective(0x0000010b),
    OMPDistributeSimdDirective(0x0000010c),
    OMPTargetParallelForSimdDirective(0x0000010d),
    OMPTargetSimdDirective(0x0000010e),
    OMPTeamsDistributeDirective(0x0000010f),
    OMPTeamsDistributeSimdDirective(0x00000110),
    OMPTeamsDistributeParallelForSimdDirective(0x00000111),
    OMPTeamsDistributeParallelForDirective(0x00000112),
    OMPTargetTeamsDirective(0x00000113),
    OMPTargetTeamsDistributeDirective(0x00000114),
    OMPTargetTeamsDistributeParallelForDirective(0x00000115),
    OMPTargetTeamsDistributeParallelForSimdDirective(0x00000116),
    OMPTargetTeamsDistributeSimdDirective(0x00000117),
    BuiltinBitCastExpr(0x00000118),
    OMPMasterTaskLoopDirective(0x00000119),
    OMPParallelMasterTaskLoopDirective(0x0000011a),
    OMPMasterTaskLoopSimdDirective(0x0000011b),
    OMPParallelMasterTaskLoopSimdDirective(0x0000011c),
    OMPParallelMasterDirective(0x0000011d),
    OMPDepobjDirective(0x0000011e),
    OMPScanDirective(0x0000011f),
    OMPTileDirective(0x00000120),
    OMPCanonicalLoop(0x00000121),
    OMPInteropDirective(0x00000122),
    OMPDispatchDirective(0x00000123),
    OMPMaskedDirective(0x00000124),
    OMPUnrollDirective(0x00000125),
    OMPMetaDirective(0x00000126),
    OMPGenericLoopDirective(0x00000127),
    OMPTeamsGenericLoopDirective(0x00000128),
    OMPTargetTeamsGenericLoopDirective(0x00000129),
    OMPParallelGenericLoopDirective(0x0000012a),
    OMPTargetParallelGenericLoopDirective(0x0000012b),
    OMPParallelMaskedDirective(0x0000012c),
    OMPMaskedTaskLoopDirective(0x0000012d),
    OMPMaskedTaskLoopSimdDirective(0x0000012e),
    OMPParallelMaskedTaskLoopDirective(0x0000012f),
    OMPParallelMaskedTaskLoopSimdDirective(0x00000130),
    OMPErrorDirective(0x00000131),
    OMPScopeDirective(0x00000132),
    LastStmt(0x00000132),
    TranslationUnit(0x0000015e),
    FirstAttr(0x00000190),
    UnexposedAttr(0x00000190),
    IBActionAttr(0x00000191),
    IBOutletAttr(0x00000192),
    IBOutletCollectionAttr(0x00000193),
    CXXFinalAttr(0x00000194),
    CXXOverrideAttr(0x00000195),
    AnnotateAttr(0x00000196),
    AsmLabelAttr(0x00000197),
    PackedAttr(0x00000198),
    PureAttr(0x00000199),
    ConstAttr(0x0000019a),
    NoDuplicateAttr(0x0000019b),
    CUDAConstantAttr(0x0000019c),
    CUDADeviceAttr(0x0000019d),
    CUDAGlobalAttr(0x0000019e),
    CUDAHostAttr(0x0000019f),
    CUDASharedAttr(0x000001a0),
    VisibilityAttr(0x000001a1),
    DLLExport(0x000001a2),
    DLLImport(0x000001a3),
    NSReturnsRetained(0x000001a4),
    NSReturnsNotRetained(0x000001a5),
    NSReturnsAutoreleased(0x000001a6),
    NSConsumesSelf(0x000001a7),
    NSConsumed(0x000001a8),
    ObjCException(0x000001a9),
    ObjCNSObject(0x000001aa),
    ObjCIndependentClass(0x000001ab),
    ObjCPreciseLifetime(0x000001ac),
    ObjCReturnsInnerPointer(0x000001ad),
    ObjCRequiresSuper(0x000001ae),
    ObjCRootClass(0x000001af),
    ObjCSubclassingRestricted(0x000001b0),
    ObjCExplicitProtocolImpl(0x000001b1),
    ObjCDesignatedInitializer(0x000001b2),
    ObjCRuntimeVisible(0x000001b3),
    ObjCBoxable(0x000001b4),
    FlagEnum(0x000001b5),
    ConvergentAttr(0x000001b6),
    WarnUnusedAttr(0x000001b7),
    WarnUnusedResultAttr(0x000001b8),
    AlignedAttr(0x000001b9),
    LastAttr(0x000001b9),
    PreprocessingDirective(0x000001f4),
    MacroDefinition(0x000001f5),
    MacroExpansion(0x000001f6),
    MacroInstantiation(0x000001f6),
    InclusionDirective(0x000001f7),
    FirstPreprocessing(0x000001f4),
    LastPreprocessing(0x000001f7),
    ModuleImportDecl(0x00000258),
    TypeAliasTemplateDecl(0x00000259),
    StaticAssert(0x0000025a),
    FriendDecl(0x0000025b),
    ConceptDecl(0x0000025c),
    FirstExtraDecl(0x00000258),
    LastExtraDecl(0x0000025c),
    OverloadCandidate(0x000002bc),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXCursorKind::class.java,
            "fromInt",
            MethodType.methodType(CXCursorKind::class.java, Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXCursorKind::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: Int): CXCursorKind = when (value) {
            0x00000001 -> UnexposedDecl
            0x00000002 -> StructDecl
            0x00000003 -> UnionDecl
            0x00000004 -> ClassDecl
            0x00000005 -> EnumDecl
            0x00000006 -> FieldDecl
            0x00000007 -> EnumConstantDecl
            0x00000008 -> FunctionDecl
            0x00000009 -> VarDecl
            0x0000000a -> ParmDecl
            0x0000000b -> ObjCInterfaceDecl
            0x0000000c -> ObjCCategoryDecl
            0x0000000d -> ObjCProtocolDecl
            0x0000000e -> ObjCPropertyDecl
            0x0000000f -> ObjCIvarDecl
            0x00000010 -> ObjCInstanceMethodDecl
            0x00000011 -> ObjCClassMethodDecl
            0x00000012 -> ObjCImplementationDecl
            0x00000013 -> ObjCCategoryImplDecl
            0x00000014 -> TypedefDecl
            0x00000015 -> CXXMethod
            0x00000016 -> Namespace
            0x00000017 -> LinkageSpec
            0x00000018 -> Constructor
            0x00000019 -> Destructor
            0x0000001a -> ConversionFunction
            0x0000001b -> TemplateTypeParameter
            0x0000001c -> NonTypeTemplateParameter
            0x0000001d -> TemplateTemplateParameter
            0x0000001e -> FunctionTemplate
            0x0000001f -> ClassTemplate
            0x00000020 -> ClassTemplatePartialSpecialization
            0x00000021 -> NamespaceAlias
            0x00000022 -> UsingDirective
            0x00000023 -> UsingDeclaration
            0x00000024 -> TypeAliasDecl
            0x00000025 -> ObjCSynthesizeDecl
            0x00000026 -> ObjCDynamicDecl
            0x00000027 -> CXXAccessSpecifier
            0x00000001 -> FirstDecl
            0x00000027 -> LastDecl
            0x00000028 -> FirstRef
            0x00000028 -> ObjCSuperClassRef
            0x00000029 -> ObjCProtocolRef
            0x0000002a -> ObjCClassRef
            0x0000002b -> TypeRef
            0x0000002c -> CXXBaseSpecifier
            0x0000002d -> TemplateRef
            0x0000002e -> NamespaceRef
            0x0000002f -> MemberRef
            0x00000030 -> LabelRef
            0x00000031 -> OverloadedDeclRef
            0x00000032 -> VariableRef
            0x00000032 -> LastRef
            0x00000046 -> FirstInvalid
            0x00000046 -> InvalidFile
            0x00000047 -> NoDeclFound
            0x00000048 -> NotImplemented
            0x00000049 -> InvalidCode
            0x00000049 -> LastInvalid
            0x00000064 -> FirstExpr
            0x00000064 -> UnexposedExpr
            0x00000065 -> DeclRefExpr
            0x00000066 -> MemberRefExpr
            0x00000067 -> CallExpr
            0x00000068 -> ObjCMessageExpr
            0x00000069 -> BlockExpr
            0x0000006a -> IntegerLiteral
            0x0000006b -> FloatingLiteral
            0x0000006c -> ImaginaryLiteral
            0x0000006d -> StringLiteral
            0x0000006e -> CharacterLiteral
            0x0000006f -> ParenExpr
            0x00000070 -> UnaryOperator
            0x00000071 -> ArraySubscriptExpr
            0x00000072 -> BinaryOperator
            0x00000073 -> CompoundAssignOperator
            0x00000074 -> ConditionalOperator
            0x00000075 -> CStyleCastExpr
            0x00000076 -> CompoundLiteralExpr
            0x00000077 -> InitListExpr
            0x00000078 -> AddrLabelExpr
            0x00000079 -> StmtExpr
            0x0000007a -> GenericSelectionExpr
            0x0000007b -> GNUNullExpr
            0x0000007c -> CXXStaticCastExpr
            0x0000007d -> CXXDynamicCastExpr
            0x0000007e -> CXXReinterpretCastExpr
            0x0000007f -> CXXConstCastExpr
            0x00000080 -> CXXFunctionalCastExpr
            0x00000081 -> CXXTypeidExpr
            0x00000082 -> CXXBoolLiteralExpr
            0x00000083 -> CXXNullPtrLiteralExpr
            0x00000084 -> CXXThisExpr
            0x00000085 -> CXXThrowExpr
            0x00000086 -> CXXNewExpr
            0x00000087 -> CXXDeleteExpr
            0x00000088 -> UnaryExpr
            0x00000089 -> ObjCStringLiteral
            0x0000008a -> ObjCEncodeExpr
            0x0000008b -> ObjCSelectorExpr
            0x0000008c -> ObjCProtocolExpr
            0x0000008d -> ObjCBridgedCastExpr
            0x0000008e -> PackExpansionExpr
            0x0000008f -> SizeOfPackExpr
            0x00000090 -> LambdaExpr
            0x00000091 -> ObjCBoolLiteralExpr
            0x00000092 -> ObjCSelfExpr
            0x00000093 -> OMPArraySectionExpr
            0x00000094 -> ObjCAvailabilityCheckExpr
            0x00000095 -> FixedPointLiteral
            0x00000096 -> OMPArrayShapingExpr
            0x00000097 -> OMPIteratorExpr
            0x00000098 -> CXXAddrspaceCastExpr
            0x00000099 -> ConceptSpecializationExpr
            0x0000009a -> RequiresExpr
            0x0000009b -> CXXParenListInitExpr
            0x0000009b -> LastExpr
            0x000000c8 -> FirstStmt
            0x000000c8 -> UnexposedStmt
            0x000000c9 -> LabelStmt
            0x000000ca -> CompoundStmt
            0x000000cb -> CaseStmt
            0x000000cc -> DefaultStmt
            0x000000cd -> IfStmt
            0x000000ce -> SwitchStmt
            0x000000cf -> WhileStmt
            0x000000d0 -> DoStmt
            0x000000d1 -> ForStmt
            0x000000d2 -> GotoStmt
            0x000000d3 -> IndirectGotoStmt
            0x000000d4 -> ContinueStmt
            0x000000d5 -> BreakStmt
            0x000000d6 -> ReturnStmt
            0x000000d7 -> GCCAsmStmt
            0x000000d7 -> AsmStmt
            0x000000d8 -> ObjCAtTryStmt
            0x000000d9 -> ObjCAtCatchStmt
            0x000000da -> ObjCAtFinallyStmt
            0x000000db -> ObjCAtThrowStmt
            0x000000dc -> ObjCAtSynchronizedStmt
            0x000000dd -> ObjCAutoreleasePoolStmt
            0x000000de -> ObjCForCollectionStmt
            0x000000df -> CXXCatchStmt
            0x000000e0 -> CXXTryStmt
            0x000000e1 -> CXXForRangeStmt
            0x000000e2 -> SEHTryStmt
            0x000000e3 -> SEHExceptStmt
            0x000000e4 -> SEHFinallyStmt
            0x000000e5 -> MSAsmStmt
            0x000000e6 -> NullStmt
            0x000000e7 -> DeclStmt
            0x000000e8 -> OMPParallelDirective
            0x000000e9 -> OMPSimdDirective
            0x000000ea -> OMPForDirective
            0x000000eb -> OMPSectionsDirective
            0x000000ec -> OMPSectionDirective
            0x000000ed -> OMPSingleDirective
            0x000000ee -> OMPParallelForDirective
            0x000000ef -> OMPParallelSectionsDirective
            0x000000f0 -> OMPTaskDirective
            0x000000f1 -> OMPMasterDirective
            0x000000f2 -> OMPCriticalDirective
            0x000000f3 -> OMPTaskyieldDirective
            0x000000f4 -> OMPBarrierDirective
            0x000000f5 -> OMPTaskwaitDirective
            0x000000f6 -> OMPFlushDirective
            0x000000f7 -> SEHLeaveStmt
            0x000000f8 -> OMPOrderedDirective
            0x000000f9 -> OMPAtomicDirective
            0x000000fa -> OMPForSimdDirective
            0x000000fb -> OMPParallelForSimdDirective
            0x000000fc -> OMPTargetDirective
            0x000000fd -> OMPTeamsDirective
            0x000000fe -> OMPTaskgroupDirective
            0x000000ff -> OMPCancellationPointDirective
            0x00000100 -> OMPCancelDirective
            0x00000101 -> OMPTargetDataDirective
            0x00000102 -> OMPTaskLoopDirective
            0x00000103 -> OMPTaskLoopSimdDirective
            0x00000104 -> OMPDistributeDirective
            0x00000105 -> OMPTargetEnterDataDirective
            0x00000106 -> OMPTargetExitDataDirective
            0x00000107 -> OMPTargetParallelDirective
            0x00000108 -> OMPTargetParallelForDirective
            0x00000109 -> OMPTargetUpdateDirective
            0x0000010a -> OMPDistributeParallelForDirective
            0x0000010b -> OMPDistributeParallelForSimdDirective
            0x0000010c -> OMPDistributeSimdDirective
            0x0000010d -> OMPTargetParallelForSimdDirective
            0x0000010e -> OMPTargetSimdDirective
            0x0000010f -> OMPTeamsDistributeDirective
            0x00000110 -> OMPTeamsDistributeSimdDirective
            0x00000111 -> OMPTeamsDistributeParallelForSimdDirective
            0x00000112 -> OMPTeamsDistributeParallelForDirective
            0x00000113 -> OMPTargetTeamsDirective
            0x00000114 -> OMPTargetTeamsDistributeDirective
            0x00000115 -> OMPTargetTeamsDistributeParallelForDirective
            0x00000116 -> OMPTargetTeamsDistributeParallelForSimdDirective
            0x00000117 -> OMPTargetTeamsDistributeSimdDirective
            0x00000118 -> BuiltinBitCastExpr
            0x00000119 -> OMPMasterTaskLoopDirective
            0x0000011a -> OMPParallelMasterTaskLoopDirective
            0x0000011b -> OMPMasterTaskLoopSimdDirective
            0x0000011c -> OMPParallelMasterTaskLoopSimdDirective
            0x0000011d -> OMPParallelMasterDirective
            0x0000011e -> OMPDepobjDirective
            0x0000011f -> OMPScanDirective
            0x00000120 -> OMPTileDirective
            0x00000121 -> OMPCanonicalLoop
            0x00000122 -> OMPInteropDirective
            0x00000123 -> OMPDispatchDirective
            0x00000124 -> OMPMaskedDirective
            0x00000125 -> OMPUnrollDirective
            0x00000126 -> OMPMetaDirective
            0x00000127 -> OMPGenericLoopDirective
            0x00000128 -> OMPTeamsGenericLoopDirective
            0x00000129 -> OMPTargetTeamsGenericLoopDirective
            0x0000012a -> OMPParallelGenericLoopDirective
            0x0000012b -> OMPTargetParallelGenericLoopDirective
            0x0000012c -> OMPParallelMaskedDirective
            0x0000012d -> OMPMaskedTaskLoopDirective
            0x0000012e -> OMPMaskedTaskLoopSimdDirective
            0x0000012f -> OMPParallelMaskedTaskLoopDirective
            0x00000130 -> OMPParallelMaskedTaskLoopSimdDirective
            0x00000131 -> OMPErrorDirective
            0x00000132 -> OMPScopeDirective
            0x00000132 -> LastStmt
            0x0000015e -> TranslationUnit
            0x00000190 -> FirstAttr
            0x00000190 -> UnexposedAttr
            0x00000191 -> IBActionAttr
            0x00000192 -> IBOutletAttr
            0x00000193 -> IBOutletCollectionAttr
            0x00000194 -> CXXFinalAttr
            0x00000195 -> CXXOverrideAttr
            0x00000196 -> AnnotateAttr
            0x00000197 -> AsmLabelAttr
            0x00000198 -> PackedAttr
            0x00000199 -> PureAttr
            0x0000019a -> ConstAttr
            0x0000019b -> NoDuplicateAttr
            0x0000019c -> CUDAConstantAttr
            0x0000019d -> CUDADeviceAttr
            0x0000019e -> CUDAGlobalAttr
            0x0000019f -> CUDAHostAttr
            0x000001a0 -> CUDASharedAttr
            0x000001a1 -> VisibilityAttr
            0x000001a2 -> DLLExport
            0x000001a3 -> DLLImport
            0x000001a4 -> NSReturnsRetained
            0x000001a5 -> NSReturnsNotRetained
            0x000001a6 -> NSReturnsAutoreleased
            0x000001a7 -> NSConsumesSelf
            0x000001a8 -> NSConsumed
            0x000001a9 -> ObjCException
            0x000001aa -> ObjCNSObject
            0x000001ab -> ObjCIndependentClass
            0x000001ac -> ObjCPreciseLifetime
            0x000001ad -> ObjCReturnsInnerPointer
            0x000001ae -> ObjCRequiresSuper
            0x000001af -> ObjCRootClass
            0x000001b0 -> ObjCSubclassingRestricted
            0x000001b1 -> ObjCExplicitProtocolImpl
            0x000001b2 -> ObjCDesignatedInitializer
            0x000001b3 -> ObjCRuntimeVisible
            0x000001b4 -> ObjCBoxable
            0x000001b5 -> FlagEnum
            0x000001b6 -> ConvergentAttr
            0x000001b7 -> WarnUnusedAttr
            0x000001b8 -> WarnUnusedResultAttr
            0x000001b9 -> AlignedAttr
            0x000001b9 -> LastAttr
            0x000001f4 -> PreprocessingDirective
            0x000001f5 -> MacroDefinition
            0x000001f6 -> MacroExpansion
            0x000001f6 -> MacroInstantiation
            0x000001f7 -> InclusionDirective
            0x000001f4 -> FirstPreprocessing
            0x000001f7 -> LastPreprocessing
            0x00000258 -> ModuleImportDecl
            0x00000259 -> TypeAliasTemplateDecl
            0x0000025a -> StaticAssert
            0x0000025b -> FriendDecl
            0x0000025c -> ConceptDecl
            0x00000258 -> FirstExtraDecl
            0x0000025c -> LastExtraDecl
            0x000002bc -> OverloadCandidate
            else -> error("enum not found")
        }
    }
}
