// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

enum class CXDiagnosticDisplayOptions(
    val `value`: Int,
) {
    SourceLocation(0x00000001),
    Column(0x00000002),
    SourceRanges(0x00000004),
    Option(0x00000008),
    CategoryId(0x00000010),
    CategoryName(0x00000020),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXDiagnosticDisplayOptions::class.java,
            "fromInt",
            MethodType.methodType(CXDiagnosticDisplayOptions::class.java, Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXDiagnosticDisplayOptions::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: Int): CXDiagnosticDisplayOptions = when (value) {
            0x00000001 -> SourceLocation
            0x00000002 -> Column
            0x00000004 -> SourceRanges
            0x00000008 -> Option
            0x00000010 -> CategoryId
            0x00000020 -> CategoryName
            else -> error("enum not found")
        }
    }
}
