// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

enum class CXIdxEntityRefKind(
    val `value`: Int,
) {
    Direct(0x00000001),
    Implicit(0x00000002),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXIdxEntityRefKind::class.java,
            "fromInt",
            MethodType.methodType(CXIdxEntityRefKind::class.java, Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXIdxEntityRefKind::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: Int): CXIdxEntityRefKind = when (value) {
            0x00000001 -> Direct
            0x00000002 -> Implicit
            else -> error("enum not found")
        }
    }
}
