// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
value class CXStringSet(
    val `$mem`: MemorySegment,
) {
    var Strings: Pointer<CXString>
        get() = StringsHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            StringsHandle.set(this.`$mem`, 0L, value)
        }

    var Count: UInt
        get() = (CountHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            CountHandle.set(this.`$mem`, 0L, value.toInt())
        }

    constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    companion object {
        val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("Strings"),
            ValueLayout.JAVA_INT.withName("Count"),
            MemoryLayout.paddingLayout(4),
        ).withName("CXStringSet")

        @JvmField
        val StringsHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("Strings"))

        @JvmField
        val CountHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("Count"))

        @JvmStatic
        fun allocate(alloc: SegmentAllocator): CXStringSet =
            CXStringSet(alloc.allocate(layout))
    }
}
