// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
value class CXString(
    val `$mem`: MemorySegment,
) {
    var `data`: Pointer<Unit>
        get() = dataHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            dataHandle.set(this.`$mem`, 0L, value)
        }

    var private_flags: UInt
        get() = (private_flagsHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            private_flagsHandle.set(this.`$mem`, 0L, value.toInt())
        }

    constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    companion object {
        val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("data"),
            ValueLayout.JAVA_INT.withName("private_flags"),
            MemoryLayout.paddingLayout(4),
        ).withName("CXString")

        @JvmField
        val dataHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("data"))

        @JvmField
        val private_flagsHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("private_flags"))

        @JvmStatic
        fun allocate(alloc: SegmentAllocator): CXString =
            CXString(alloc.allocate(layout))
    }
}
