// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

enum class CXTokenKind(
    val `value`: Int,
) {
    Punctuation(0x00000000),
    Keyword(0x00000001),
    Identifier(0x00000002),
    Literal(0x00000003),
    Comment(0x00000004),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXTokenKind::class.java,
            "fromInt",
            MethodType.methodType(CXTokenKind::class.java, Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXTokenKind::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: Int): CXTokenKind = when (value) {
            0x00000000 -> Punctuation
            0x00000001 -> Keyword
            0x00000002 -> Identifier
            0x00000003 -> Literal
            0x00000004 -> Comment
            else -> error("enum not found")
        }
    }
}
