// this file is auto generated by endoqa kotlin ffi, modify it with caution
package clang.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

enum class CXVisitorResult(
    val `value`: Int,
) {
    Break(0x00000000),
    Continue(0x00000001),
    ;

    companion object {
        @JvmStatic
        val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            CXVisitorResult::class.java,
            "fromInt",
            MethodType.methodType(CXVisitorResult::class.java, Int::class.java)
        )

        @JvmStatic
        val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            CXVisitorResult::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        fun fromInt(`value`: Int): CXVisitorResult = when (value) {
            0x00000000 -> Break
            0x00000001 -> Continue
            else -> error("enum not found")
        }
    }
}
