// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.llvm

import java.lang.foreign.Arena
import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.SegmentAllocator
import java.lang.foreign.StructLayout
import java.lang.foreign.ValueLayout
import java.lang.invoke.VarHandle
import kotlin.Boolean
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmInline
import kotlin.jvm.JvmStatic

@JvmInline
public value class LLVMOrcCJITDylibSearchOrderElement(
  public val `$mem`: MemorySegment,
) {
  public var JD: LLVMOrcJITDylibRef
    get() = LLVMOrcCJITDylibSearchOrderElement.JDHandle.get(this.`$mem`, 0L) as MemorySegment
    set(`value`) {
      LLVMOrcCJITDylibSearchOrderElement.JDHandle.set(this.`$mem`, 0L, value)
    }

  public var JDLookupFlags: LLVMOrcJITDylibLookupFlags
    get() =
          LLVMOrcJITDylibLookupFlags.fromInt(LLVMOrcCJITDylibSearchOrderElement.JDLookupFlagsHandle.get(this.`$mem`,
          0L) as Int)
    set(`value`) {
      LLVMOrcCJITDylibSearchOrderElement.JDLookupFlagsHandle.set(this.`$mem`, 0L,value.value)
    }

  public constructor(gc: Boolean) : this(kotlin.run {
      require(gc) { "Do not call this if gc is not want" }
      Arena.ofAuto().allocate(LLVMOrcCJITDylibSearchOrderElement.layout)
  })

  public companion object {
    public val layout: StructLayout = MemoryLayout.structLayout(
      `$RuntimeHelper`.POINTER.withName("JD"),
      ValueLayout.JAVA_INT.withName("JDLookupFlags"),
      java.lang.foreign.MemoryLayout.paddingLayout(4),
    ).withName("LLVMOrcCJITDylibSearchOrderElement")

    @JvmField
    public val JDHandle: VarHandle = layout.varHandle(MemoryLayout.PathElement.groupElement("JD"))

    @JvmField
    public val JDLookupFlagsHandle: VarHandle =
        layout.varHandle(MemoryLayout.PathElement.groupElement("JDLookupFlags"))

    @JvmStatic
    public fun allocate(alloc: SegmentAllocator): LLVMOrcCJITDylibSearchOrderElement =
        LLVMOrcCJITDylibSearchOrderElement(alloc.allocate(LLVMOrcCJITDylibSearchOrderElement.layout))
  }
}
